README.md, package.json, packages/react/src/components/ErrorMessage/ErrorMessage.module.css, packages/react/src/components/ErrorMessage/ErrorMessage.stories.mdx, packages/react/src/components/ErrorMessage/ErrorMessage.test.tsx, packages/react/src/components/ErrorMessage/ErrorMessage.tsx, packages/react/src/components/ErrorMessage/index.ts, packages/react/src/components/FieldSet/FieldSet.module.css, packages/react/src/components/FieldSet/FieldSet.stories.mdx, packages/react/src/components/FieldSet/FieldSet.test.tsx, packages/react/src/components/FieldSet/FieldSet.tsx, packages/react/src/components/FieldSet/index.ts, packages/react/src/components/Tabs/Tabs.module.css, packages/react/src/components/Tabs/Tabs.tsx, packages/react/src/components/index.ts, yarn.lock
Copied a couple of basic components from Altinn's design system.
=> Add FieldSet and ErrorMessage components

packages/react/src/components/Checkbox/Checkbox.test.tsx, packages/react/src/components/Checkbox/Checkbox.tsx, packages/react/src/components/CheckboxGroup/CheckboxGroup.test.tsx, packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx, packages/react/src/components/FieldSet/FieldSet.test.tsx, packages/react/src/components/FieldSet/FieldSet.tsx, packages/react/src/components/RadioButton/RadioButton.test.tsx, packages/react/src/components/RadioButton/RadioButton.tsx, packages/react/src/components/RadioGroup/RadioGroup.test.tsx, packages/react/src/components/RadioGroup/RadioGroup.tsx, packages/react/src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.tsx
Applied changes from https://github.com/Altinn/altinn-design-system/pull/254. Related issue: #32
=> React nodes in checkboxes and radio buttons

packages/react/src/components/Button/Button.module.css, packages/react/src/components/Button/Button.stories.mdx, packages/react/src/components/Button/Button.test.tsx, packages/react/src/components/Button/Button.tsx, packages/react/src/components/Button/index.ts, packages/react/src/components/index.ts
Other changes:
- Added property controls for the canvas
- Replaced BEM classes and made some small improvements to the CSS code
- Minor code simplifications in tests
=> fix(button): Export button props

packages/react/src/components/TextArea/TextArea.module.css, packages/react/src/components/TextArea/TextArea.stories.mdx, packages/react/src/components/TextArea/TextArea.test.tsx, packages/react/src/components/TextArea/TextArea.tsx, packages/react/src/components/TextArea/index.ts, packages/react/src/components/_InputWrapper/utils.ts, packages/react/src/components/index.ts
Copy of `TextArea` from [@altinn/altinn-design-system](https://github.com/Altinn/altinn-design-system).
=> feat(textarea): Add TextArea component

packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx
- Added a check for updates in the `value` property in order to synchronize the selected value(s).
- Fixed failing tests.
Related issue: https://github.com/Altinn/altinn-studio/issues/9606
=> fix(select): Value update in Select component

packages/react/src/components/TextField/TextField.stories.mdx, packages/react/src/components/TextField/TextField.test.tsx, packages/react/src/components/TextField/TextField.tsx, packages/react/src/components/TextField/index.ts, packages/react/src/components/index.ts
Copy of `TextField` from Altinn's design system.
=> feat(textfield): Add text field component

packages/react/src/components/Button/index.ts, packages/react/src/components/TextArea/index.ts, packages/react/src/components/index.ts
Made all type exports separate from normal exports. Hopefully this will solve the import issues consumers are having.
=> fix: Export issues

packages/react/src/components/Tabs/Tabs.module.css, packages/react/src/components/Tabs/Tabs.tsx
- Corrected class name of tablist
- Adjusted some CSS values (these should be replaced by Figma tokens in the future)
=> fix(Tabs): Spacing issues

package.json, packages/react/src/components/Button/Button.module.css, packages/react/src/components/Checkbox/Checkbox.module.css, packages/react/src/components/FieldSet/FieldSet.module.css, packages/react/src/components/HelpText/HelpText.module.css, packages/react/src/components/Popover/Popover.module.css, packages/react/src/components/RadioButton/RadioButton.module.css, packages/react/src/components/Select/Select.module.css, packages/react/src/components/Tabs/Tabs.module.css, packages/react/src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.module.css, packages/react/src/components/_InputWrapper/InputWrapper.module.css, yarn.lock
Update Figma tokens to version 6.
- #103
=> fix: Update Figma tokens

package.json, packages/react/src/components/Select/Select.module.css, packages/react/src/components/_InputWrapper/InputWrapper.module.css, yarn.lock
- https://github.com/Altinn/altinn-studio/issues/9747
=> fix: Set font and min height on input fields

packages/react/src/components/Accordion/Accordion.module.css, packages/react/src/components/Accordion/Accordion.stories.mdx, packages/react/src/components/Accordion/Accordion.test.tsx, packages/react/src/components/Accordion/Accordion.tsx, packages/react/src/components/Accordion/AccordionContent.tsx, packages/react/src/components/Accordion/AccordionHeader.module.css, packages/react/src/components/Accordion/AccordionHeader.test.tsx, packages/react/src/components/Accordion/AccordionHeader.tsx, packages/react/src/components/Accordion/AccordionIcon.module.css, packages/react/src/components/Accordion/AccordionIcon.tsx, packages/react/src/components/Accordion/Context.ts, packages/react/src/components/Accordion/icons/Arrow.tsx, packages/react/src/components/Accordion/icons/CircleArrow.tsx, packages/react/src/components/Accordion/icons/index.ts, packages/react/src/components/Accordion/index.ts, packages/react/src/components/index.ts
Copy of `Accordion` from Altinn's design system.
- https://github.com/Altinn/altinn-design-system/issues/235
=> feat(Accordion): Add accordion component

packages/react/src/components/Accordion/Accordion.tsx, packages/react/src/components/Accordion/AccordionContent.tsx, packages/react/src/components/Accordion/AccordionHeader.tsx, packages/react/src/components/Accordion/AccordionIcon.tsx, packages/react/src/components/Button/Button.tsx, packages/react/src/components/Checkbox/Checkbox.tsx, packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx, packages/react/src/components/ErrorMessage/ErrorMessage.tsx, packages/react/src/components/FieldSet/FieldSet.tsx, packages/react/src/components/HelpText/HelpText.tsx, packages/react/src/components/Popover/Popover.tsx, packages/react/src/components/RadioButton/RadioButton.tsx, packages/react/src/components/RadioGroup/RadioGroup.tsx, packages/react/src/components/Select/MultiSelectItem.tsx, packages/react/src/components/Select/Select.tsx, packages/react/src/components/SvgIcon/SvgIcon.tsx, packages/react/src/components/Tabs/Tabs.tsx, packages/react/src/components/TextArea/TextArea.tsx, packages/react/src/components/TextField/TextField.tsx
Added displayName to exported components so that they can be used in code examples.
=> fix: added displayName to all exported components

packages/react/src/components/HelpText/index.ts, packages/react/src/components/index.ts
=> fix(HelpText):export help text size prop

packages/react/src/components/Select/MultiSelect.stories.mdx, packages/react/src/components/Select/Select.module.css, packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx, packages/react/src/components/Select/SingleSelect.stories.mdx, packages/react/src/components/Select/utils.test.ts, packages/react/src/components/Select/utils.ts, packages/react/src/utils/compareFunctions.test.ts, packages/react/src/utils/compareFunctions.ts, packages/react/src/utils/index.ts, packages/react/src/utils/sortUtils.test.ts, packages/react/src/utils/sortUtils.ts, packages/react/src/utils/stringUtils.test.ts, packages/react/src/utils/stringUtils.ts
- Added an input field for searching in the `Select` component. It calls a sorting function that orders the options by how well the search keyword matches with labels and optional keywords given on each option.
- Added an optional `formattedLabel` property to the option types. This lets the consumer format the labels in the option list.
=> feat(Select): Search and formatting

.eslintrc.js, packages/react/src/components/Spinner/Spinner.module.css, packages/react/src/components/Spinner/Spinner.stories.mdx, packages/react/src/components/Spinner/Spinner.test.tsx, packages/react/src/components/Spinner/Spinner.tsx, packages/react/src/components/Spinner/index.ts, packages/react/src/components/index.ts
Created the new spinner component based on Figma sketch. https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles---Core-Components?node-id=9104%3A49626&t=E0vLjMXEaaBIgtzU-0
=> feat(Spinner): Add spinner component

packages/react/README.md, packages/react/package.json, yarn.lock
resolves #154
- Added just the missing packages you get errors as missing when installing and running in a new application
- Added a short README, should probably be improved upon in the future
=> chore: Add missing react package dependencies

packages/react/src/components/_InputWrapper/InputWrapper.module.css
Font size on text fields was not set.
=> fix: Set correct font size in all text input fields

package.json, packages/react/src/components/ToggleButtonGroup/ToggleButtonGroup.module.css, packages/react/src/components/ToggleButtonGroup/ToggleButtonGroup.stories.mdx, packages/react/src/components/ToggleButtonGroup/ToggleButtonGroup.test.tsx, packages/react/src/components/ToggleButtonGroup/ToggleButtonGroup.tsx, packages/react/src/components/ToggleButtonGroup/index.ts, packages/react/src/components/index.ts
Created a new `ToggleButtonGroup` component inspired by the one in Altinn's design system.
=> feat: Add toggle button component

packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx
- Make the given initial value appear in the single select
- Update the search field value when the user presses Enter in a single select
=> fix(Select): Display initial value on single select

storefront/layouts/NavigationPageLayout/NavigationPageLayout.tsx, storefront/pages/god-praksis/designprinsipper.mdx, storefront/pages/god-praksis/index.mdx, storefront/pages/god-praksis/innholdsarbeid.mdx, storefront/pages/grunnleggende/design/for-designere.mdx, storefront/pages/grunnleggende/index.mdx, storefront/pages/grunnleggende/styling/design-tokens.mdx
docs: started working on content for designers, removed some lorem ipsum
=> docs: design-content

.storybook/main.ts, package.json, yarn.lock
Added `@storybook/addon-a11y` for some accessibility testing in stories :)
=> docs: :wheelchair: Add Storybook a11y addon

packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx
=> fix(Select): Collapse when arrow button is clicked

packages/react/src/components/Select/MultiSelectItem.tsx, packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx
=> fix(Select): Set "button" type on buttons

packages/react/CHANGELOG.md, packages/react/package.json
- @digdir/design-system-react@0.11.3
=> chore: Update @digdir/design-system-react to 0.11.3

design-tokens/Base/Semantic.json, design-tokens/Mode/Compact.json
solves https://github.com/digdir/designsystem/issues/350
=> style: added size tokens for components

design-tokens/Base/Semantic.json
resolves https://github.com/digdir/designsystem/issues/377
=> style: added tokens for body short

design-tokens/$metadata.json, design-tokens/$themes.json, design-tokens/Base/Semantic.json, design-tokens/Brand/Altinn.json, design-tokens/Viewport/@1200.json, design-tokens/Viewport/@1440.json, design-tokens/Viewport/@375.json, design-tokens/Viewport/@576.json, design-tokens/Viewport/@992.json
Resolves https://github.com/digdir/designsystem/issues/305
=> style: added color palette for altinn brand

design-tokens/Base/Semantic.json, design-tokens/Mode/Compact.json
=> style: added token for header xxsmall h6

design-tokens/$themes.json, design-tokens/Base/Semantic.json, design-tokens/Mode/Compact.json
We already have xsmall (f-2) size within the paragraph tokens
=> style: removed tokens for detail

packages/react/src/components/Accordion/Accordion.module.css
Update to use new token names that was changed in #392
=> chore(Accordion): :recycle: Update to use new spacing & sizing tokens names

packages/react/CHANGELOG.md, packages/react/package.json, packages/tokens/CHANGELOG.md, packages/tokens/package.json, yarn.lock
=> chore: Release next version of tokens & react

packages/tokens/brand/altinn/tokens.cjs.js, packages/tokens/brand/altinn/tokens.css, packages/tokens/brand/altinn/tokens.d.ts, packages/tokens/brand/altinn/tokens.esm.js, packages/tokens/brand/digdir/tokens.cjs.js, packages/tokens/brand/digdir/tokens.css, packages/tokens/brand/digdir/tokens.d.ts, packages/tokens/brand/digdir/tokens.esm.js, packages/tokens/brand/tilsynet/tokens.cjs.js, packages/tokens/brand/tilsynet/tokens.css, packages/tokens/brand/tilsynet/tokens.d.ts, packages/tokens/brand/tilsynet/tokens.esm.js, packages/tokens/build.ts
Removed date from tokens files header as to not trigger new diff in git each time new tokens are built
=> chore(tokens): :memo: Changed file header for generated token files

packages/react/package.json, packages/react/src/components/Popover/Popover.tsx, yarn.lock
Updated Floating UI and adjusted to breaking changes in version 0.24.0. Resolves #387.
=> build: Update Floating UI to latest version

storefront/components/ResponsiveIframe/ResponsiveIframe.module.css, storefront/components/ResponsiveIframe/ResponsiveIframe.tsx, storefront/pages/god-praksis/tilgjengelighet/forsta-synsnedsettelse.mdx
Added a `ResponsiveIframe` component to the storefront that allows iframe to be displayed in 16-9 and 4-3 aspect ratios.
=> chore: added responsive iframe

packages/react/src/components/Accordion/AccordionHeader.tsx
=> fix(Accordion): :bug: Use correct icon in header

design-tokens/$metadata.json, design-tokens/$themes.json, design-tokens/Base/Core.json, design-tokens/Base/Semantic.json, design-tokens/Viewport/@320.json
=> style: fluid typescale improvements

storefront/components/ImageSection/ImageSection.module.css
Resolves #457
Made buttons responsive and take full width on mobile.
=> chore: made ImageSection buttons responsive (storefront)

packages/react/src/components/Select/Select.module.css, packages/react/src/components/Tabs/Tabs.module.css, packages/react/src/components/ToggleButtonGroup/ToggleButtonGroup.module.css, packages/react/src/components/_InputWrapper/InputWrapper.module.css
=> fix(InputWrapper, Select, Tabs, ToggleButtonGroup): :recycle: Removed component defined font-family

storefront/pages/god-praksis/tilgjengelighet/forsta-synsnedsettelse.mdx
more clear what the content is about.
=> docs: 📄 Article about visual impairment (Brreg)

storefront/pages/grunnleggende/designelementer/typografi.mdx, storefront/pages/grunnleggende/introduksjon/verdier.mdx
=> docs: content improvements typography and values

storefront/pages/grunnleggende/designelementer/typografi.mdx
=> docs: simplified typography table

storefront/components/ImageSection/ImageSection.module.css, storefront/components/MdxContent/MdxContent.module.css, storefront/layouts/MenuPageLayout/MenuPageLayout.module.css
=> chore: styling fixes and code styling (storefront)

packages/react/src/components/Select/OptionList/OptionList.tsx
=> fix(Select): :bug: Add zindex to dropdown

packages/react/src/components/FieldSet/FieldSet.test.tsx, packages/react/src/components/FieldSet/FieldSet.tsx
=> fix(FieldSet): :wheelchair: Fix wrong role on `ErrorMessage`

packages/react/src/components/Checkbox/Checkbox.module.css
resolves: #163 
Fix to avoid "jumping" while checking/unchecking the checkbox.
=> fix(Checkbox): should avoid different box-size when checked/unchecked

design-tokens/Base/Semantic.json
Created `xsmall` token for error message.
=> feat(Tokens): add xsmall errormessage

packages/react/src/components/Typography/ErrorMessage/ErrorMessage.module.css, packages/react/src/components/Typography/ErrorMessage/ErrorMessage.tsx
Resolves: #548 
Added the new xsmall size to error-message.
=> feat(ErrorMessage): added xsmall options

README.md
docs: Update README.md with link to Storybook
=> docs: Update README.md with link to Storybook

packages/react/src/components/Checkbox/Checkbox.stories.tsx
Made the preview panel interactive. :)
=> docs(Checkbox): story should be interactive

packages/react/src/components/Typography/ErrorMessage/ErrorMessage.module.css, packages/react/src/components/Typography/Heading/Heading.module.css, packages/react/src/components/Typography/Ingress/Ingress.module.css, packages/react/src/components/Typography/Label/Label.module.css, packages/react/src/components/Typography/Paragraph/Paragraph.module.css
resolves: #472 
Fixed the correct spacing based on the typography size. :)
=> fix(Typography): fixed spacing

packages/react/src/components/index.ts
What to export is already defined within each component directory, no need to do it twice.
=> refactor: Export all in components/index.ts

packages/react/src/components/Chip/Chip.mdx, packages/react/src/components/Chip/Chip.stories.tsx, packages/react/src/components/Chip/Chip.tsx, packages/react/src/components/Chip/Removable/Removable.module.css, packages/react/src/components/Chip/Removable/Removable.tsx, packages/react/src/components/Chip/_ChipButton/ChipButton.module.css, packages/react/src/components/Chip/_ChipButton/ChipButton.tsx
Resolves: #608 
Some issues were found on the Chip component after some more testing. Should be resolved within this PR.
=> fix(Chip): visual improvements

storefront/pages/god-praksis/brukerinnsikt/brukergrupper-som-er-digitalt-sarbare.mdx, storefront/pages/god-praksis/brukerinnsikt/brukerreise-for-din-tjeneste.mdx, storefront/pages/god-praksis/brukerinnsikt/i-innbyggeren-sine-sko.mdx, storefront/pages/god-praksis/brukerinnsikt/seks-typiske-brukergrupper.mdx, storefront/pages/god-praksis/index.mdx
=> docs: 📄 Articles from BiOS

packages/react/src/components/Chip/Chip.module.css, packages/react/src/components/Chip/Chip.tsx, packages/react/src/components/Chip/Removable/Removable.module.css, packages/react/src/components/Chip/Removable/Removable.tsx, packages/react/src/components/Chip/_ChipButton/ChipButton.module.css
Suggestion for PR #662 on flex container to simplify code
=> style(Chip): :lipstick: Update `Chip` flex container

packages/react/src/components/Chip/Chip.mdx, packages/react/src/components/Chip/Chip.stories.tsx, packages/react/src/components/Chip/Chip.test.tsx, packages/react/src/components/Chip/Chip.tsx, packages/react/src/components/Chip/Group/Group.tsx, packages/react/src/components/Chip/Removable/Removable.tsx, packages/react/src/components/Chip/_ChipButton/ChipButton.test.tsx, packages/react/src/components/Chip/_ChipButton/ChipButton.tsx, packages/react/src/components/Chip/index.ts, yarn.lock
resolves: #661 
Some clean-ups and improvements after talking with @mimarz 👍
=> refactor(Chip): simplify chip component with some clean-ups

packages/react/src/components/Button/Button.module.css, packages/react/src/components/Button/Button.test.tsx, packages/react/src/components/Button/Button.tsx
=> fix(Button): Correct sizes when only icon is used

packages/react/src/components/Button/Button.module.css
=> fix(Button): :wheelchair: Added 44px clickbound for `small` size

packages/react/src/components/Button/Button.module.css
=> fix(Button): :bug: Fix icon being clipped in Firefox browser

packages/react/src/utility-components/AnimateHeight/AnimateHeight.tsx
Wrapped `setHeight` in `ResizeObserver` in order to call it every time the height changes.
=> fix(Accordion): Support dynamic height

packages/react/src/components/Chip/Removable/Removable.tsx
=> fix(Chip.Removable): :bug: Use correct button type to avoid default submit

packages/react/src/components/Chip/Toggle/Toggle.tsx
Changes after feedback on how this component was used
=> feat(Chip.Toggle): ♻️ Enabled `checkmark` as default when `selected`

packages/react/src/components/form/Radio/Group/Group.tsx
Updated "value" types to match `Radio` value and `onChange` callback
=> refactor(Radio): :label: Updated `Radio.Group` types for value

packages/react/src/components/form/Checkbox/Checkbox.module.css, packages/react/src/components/form/Checkbox/Checkbox.tsx, packages/react/src/components/form/Checkbox/Group/Group.module.css, packages/react/src/components/form/Checkbox/Group/Group.tsx, packages/react/src/components/form/Fieldset/Fieldset.module.css, packages/react/src/components/form/Fieldset/Fieldset.tsx, packages/react/src/components/form/Radio/Group/Group.module.css, packages/react/src/components/form/Radio/Group/Group.tsx, packages/react/src/components/form/Radio/Radio.module.css, packages/react/src/components/form/Radio/Radio.tsx
=> fix(Checkbox, Radio, Fieldset): :bug: Make sure spacings are only applied when needed

packages/react/src/components/Pagination/Pagination.module.css, packages/react/src/components/Pagination/Pagination.test.tsx, packages/react/src/components/Pagination/Pagination.tsx
fixes #739
- Cleaned up some CSS
- Fixed ellipsis not being align properly
- Use correct ellipsis character instead of three punctuation (... vs …)
=> fix(Pagination): :bug: Fix compact spacings and ellipsis alignment

docs-components/Information/Information.module.css, docs-components/Information/Information.tsx, packages/react/src/components/Alert/Alert.mdx, packages/react/src/components/Alert/Alert.stories.tsx
=> docs: improved alert guidelines

lerna.json, package.json, yarn.lock
kept having problems with broken lock files after running version cmd, hopefully this fixes it
=> chore: :construction_worker: Upgrade Lerna

packages/react/src/components/Alert/Alert.mdx, packages/react/src/components/Alert/Alert.stories.tsx, packages/react/src/components/Button/Button.mdx, packages/react/src/components/Pagination/Pagination.mdx, packages/react/src/components/Spinner/Spinner.stories.mdx, packages/react/src/components/Tag/Tag.mdx, packages/react/src/components/Typography/Typography.mdx, packages/react/src/components/form/Checkbox/Group/Group.stories.tsx, packages/react/src/components/form/Fieldset/Fieldset.mdx
Fixed some typos in the stories.
=> docs: Fix typos

storefront/package.json, storefront/pages/_app.tsx, yarn.lock
Added Vercel Web Analytics to the Storefront. It's privacy-friendly and does not store any cookies.
Followed this tutorial: https://vercel.com/docs/analytics/quickstart
=> chore: Added web analytics to the storefront

.github/workflows/deploy-storybook.yml, .gitignore, package.json
Created new `dist` folder for build stuff in root. We need the docs folder for actual docs stuff :) 
Will update the Settings -> Pages to the correct folder once the updated workflow runs :)
=> chore: :building_construction: Change Storybook build folder

packages/react/package.json, packages/react/src/components/Popover/Popover.tsx, yarn.lock
Updated Floating UI and adjusted to breaking changes on typing.
=> build(Floating UI): Update to latest

storefront/components/Footer/Footer.tsx, storefront/pages/grunnleggende/introduksjon/slack.mdx, storefront/pages/index.mdx
=> docs: added information about new slack

packages/react/src/components/Button/Button.module.css, packages/react/src/components/Chip/_ChipBase/ChipBase.module.css, packages/react/src/components/form/Checkbox/Checkbox.module.css, packages/react/src/components/form/Radio/Radio.module.css
=> fix(Radio, Checkbox, Button, Chip.Toggle): Remove sticky hover on touch devices

packages/react/src/components/form/Textfield/Textfield.module.css, packages/react/src/components/form/Textfield/Textfield.test.tsx, packages/react/src/components/form/Textfield/Textfield.tsx
Fixed wrong spelling of the "suffix" property. Also changed the name of the test file so it is the same as the component.
=> fix(Textfield): Prop typo

packages/react/src/components/form/Textarea/Textarea.mdx, packages/react/src/components/form/Textarea/Textarea.module.css, packages/react/src/components/form/Textarea/Textarea.stories.tsx, packages/react/src/components/form/Textarea/Textarea.test.tsx, packages/react/src/components/form/Textarea/Textarea.tsx, packages/react/src/components/form/Textarea/index.ts, packages/react/src/components/form/Textarea/useTextarea.ts, packages/react/src/components/form/useFormField.ts
=> feat(Textarea): :sparkles: New `Textarea` component

packages/react/src/components/Alert/Alert.mdx
=> chore: Remove margin on stack component wrapping do and dont in storybook

docs-components/Stack/Stack.module.css, packages/react/src/components/Alert/Alert.mdx
=> chore: remove stack margin

packages/react/src/components/Select/OptionList/OptionList.module.css, packages/react/src/components/Select/OptionList/OptionList.test.tsx, packages/react/src/components/Select/OptionList/OptionList.tsx, packages/react/src/components/Select/Select.tsx
Solves the following issue in Altinn Studio: https://github.com/Altinn/altinn-studio/issues/11334
=> fix(Select): Hide list when reference is hidden

packages/react/src/components/Button/Button.tsx
=> feat(Button): :sparkles: Support for overriding html element using `as`

packages/react/src/components/index.ts
=> fix: Add missing export `ToggleGroup`

package.json, packages/react/tsconfig.json, packages/tokens/package.json, tsconfig.json, yarn.lock
=> chore: update tsconfig

packages/react/src/components/form/NativeSelect/NativeSelect.tsx, packages/react/src/components/form/Textarea/Textarea.tsx, packages/react/src/components/form/Textfield/Textfield.tsx
=> feat: Add `htmlSize` to `NativeSelect` and `Textfield`

packages/react/src/components/List/List.module.css, packages/react/src/components/List/List.tsx, packages/react/src/components/List/ListItem/ListItem.module.css, packages/react/src/components/List/ListItem/ListItem.tsx
=> fix(List): Add more spacing between items

packages/react/src/components/Popover/Popover.stories.tsx
=> docs(Popover): Change `useState` to `useRef`

packages/react/src/components/form/Switch/Switch.module.css, packages/react/src/components/form/Switch/Switch.stories.tsx, packages/react/src/components/form/Switch/Switch.tsx
=> fix(Switch): Remove `gap` when there is no children

packages/react/src/components/_InputWrapper/InputWrapper.tsx
=> fix(InputWrapper): Remove gap

packages/react/src/components/HelpText/HelpText.test.tsx, packages/react/src/components/HelpText/HelpText.tsx
=> fix(HelpText): Add missing `aria-expanded`

packages/react/src/components/Popover/Popover.mdx, packages/react/src/components/Popover/Popover.stories.tsx
Tells user to add `aria-expanded`, and update stories to use it.
=> docs(Popover): Add `aria-expanded`

packages/react/src/components/form/NativeSelect/NativeSelect.module.css, packages/react/src/components/form/NativeSelect/NativeSelect.tsx
=> style(NativeSelect): Add caret and hover color

packages/react/src/components/List/List.mdx, packages/react/src/components/List/List.stories.tsx
=> docs(List): Add showcase of list of links

packages/react/src/components/HelpText/HelpText.module.css, packages/react/src/components/HelpText/HelpText.tsx
=> style(HelpText): Use new tokens

packages/react/src/components/form/Switch/Switch.module.css
=> fix(Switch): :bug: Should reduce-motion

packages/react/src/components/Box/Box.mdx, packages/react/src/components/Box/Box.module.css, packages/react/src/components/Box/Box.stories.tsx, packages/react/src/components/Box/Box.test.tsx, packages/react/src/components/Box/Box.tsx
=> feat(Box): add `forwardRef`, make props default `undefined`

packages/react/src/components/form/NativeSelect/NativeSelect.module.css
Noticed is was abit small, saw it was to small according to Figma.
=> style(NativeSelect): :lipstick: Bump left padding according to Figma

apps/storefront/pages/grunnleggende/introduksjon/om-designsystemet.mdx
=> docs: updated information about the designsystem

packages/react/src/components/DropdownMenu/DropdownMenu.module.css
=> fix(DropdownMenu): :bug: Add missing z-index

packages/react/src/components/Chip/Group/Group.stories.tsx, packages/react/src/components/Chip/Toggle/Toggle.tsx
=> fix(Chip.Toggle): Make Chip.Toggle fallback on context size

packages/react/src/components/Box/Box.tsx, packages/react/src/components/index.ts
=> chore(Box): Export Box component

packages/react/src/components/Button/Button.module.css
=> style(Button): Extend padding

packages/react/src/components/Divider/Divider.module.css, packages/react/src/components/Divider/Divider.tsx
=> feat(Divider): :lipstick: Adjusted size

packages/react/src/components/Popover/Popover.module.css, packages/react/src/components/Popover/Popover.tsx
=> fix(Popover): wrong border size on arrow

packages/react/src/components/form/Textarea/Textarea.tsx, packages/react/src/components/form/Textfield/Textfield.tsx, packages/react/src/components/form/useFormField.test.tsx
=> fix(Textfield, Textarea): :bug: Only apply `aria-describedby` if its defined

packages/css/nativeselect.css, packages/css/search.css, packages/css/textarea.css, packages/css/textfield.css, packages/react/src/components/form/NativeSelect/NativeSelect.module.css, packages/react/src/components/form/Search/Search.module.css, packages/react/src/components/form/Textarea/Textarea.module.css, packages/react/src/components/form/Textfield/Textfield.module.css
We were not checking if `aria-disabled` was set in our disabled styles
=> style: add missing `[aria-disabled]` on disbled states

packages/react/src/components/Accordion/Accordion.module.css
=> fix(Accordion): support for using custom elements inside `Item` and `Header`

packages/react/src/components/Chip/Chip.module.css, packages/react/src/components/Chip/Removable/Removable.stories.tsx, packages/react/src/components/Chip/Toggle/Toggle.stories.tsx
=> fix(Chip): :bug: Add missing disabled styling and behaviour

packages/react/src/components/Typography/ErrorMessage/ErrorMessage.tsx
=> fix(ErrorMessage): Change default wrapper to `div`

packages/react/src/components/form/Search/Search.module.css
=> fix(Search): :bug: Fix missaligned search icon

packages/react/src/components/ToggleGroup/ToggleGroupItem/ToggleGroupItem.module.css, packages/react/src/components/ToggleGroup/ToggleGroupItem/ToggleGroupItem.tsx
=> fix(ToggleGroup): :bug: Use correct paddings on `ToggleGroup.Item`

packages/react/src/components/List/List.test.tsx, packages/react/src/components/List/List.tsx
=> fix(List): Wrap in `div` to allow access to `Heading`

packages/react/src/components/ToggleGroup/ToggleGroup.module.css
=> fix(ToggleGroup): Only use needed space for buttons

packages/react/src/components/Pagination/Pagination.module.css
=> fix(Pagination): Only use needed space for buttons

packages/react/src/components/Accordion/Accordion.module.css
=> fix(Accordion): 🐛 Fix wrong border colors for `first`, `second`, `third` colors

packages/react/src/components/DropdownMenu/DropdownMenu.module.css
=> fix(DropdownMenu): :bug: Add missing background

packages/react/src/components/form/Switch/Switch.module.css
=> fix(Switch): :bug: Prevent from being clamped in flex container

packages/tokens/scripts/build.ts
We need this transformers to support this: https://docs.tokens.studio/tokens/color-modifiers
=> build(tokens): :construction_worker: Add support for token studio color modifiers

packages/react/src/components/DropdownMenu/DropdownMenu.tsx, packages/react/src/components/Popover/Popover.tsx, packages/react/src/hooks/index.ts, packages/react/src/hooks/useIsomorphicLayoutEffect.ts, packages/react/src/hooks/useSynchronizedAnimation.ts
=> chore: Replace `useLayoutEffect` with `useIsomorphicLayoutEffect`

.github/workflows/build-tokens.yml, .github/workflows/check-storefront.yml, .github/workflows/checks-packages.yml, .github/workflows/cleanup-preview-deployments.yml, .github/workflows/create-preview-comment.yml, .github/workflows/development-deploy.yml, .github/workflows/storefront-deploy.yml, .github/workflows/storefront-preview.yml, .github/workflows/storybook-deploy-vercel.yml, .github/workflows/storybook-deploy.yml, .github/workflows/storybook-preview.yml
=> chore: :construction_worker: Upgrade to Github actions v4

packages/react/src/components/Box/Box.module.css, packages/react/src/components/Box/Box.tsx
=> feat(Box): Add new border radius tokens

packages/react/src/components/form/Combobox/Combobox.mdx, packages/react/src/components/form/Combobox/Combobox.stories.tsx
=> docs(Combobox): Add preselected and outside chips stories

packages/react/src/components/DropdownMenu/DropdownMenu.mdx, packages/react/src/components/DropdownMenu/DropdownMenu.stories.tsx, packages/react/src/components/DropdownMenu/DropdownMenu.tsx, packages/react/src/components/form/Combobox/Combobox.tsx, packages/react/src/types/Portal.ts
=> feat(DropdownMenu): Add portal support

packages/react/src/components/Popover/Popover.mdx, packages/react/src/components/Popover/Popover.stories.tsx, packages/react/src/components/Popover/Popover.tsx
=> feat(Popover): Add portal support

packages/react/src/components/Tooltip/Tooltip.mdx, packages/react/src/components/Tooltip/Tooltip.stories.tsx, packages/react/src/components/Tooltip/Tooltip.tsx, packages/react/src/types/Portal.ts
=> feat(Tooltip): Add portal support

packages/react/package.json, packages/react/src/components/Box/Box.stories.tsx, packages/react/src/components/Box/Box.test.tsx, packages/react/src/components/Box/Box.tsx, yarn.lock
=> feat(Box): Add support for changing element type with `asChild`

packages/react/src/components/form/Search/Search.module.css
=> fix(Search): Scale input height based on sizing prop

packages/react/src/components/Tooltip/Tooltip.mdx, packages/react/src/components/Tooltip/Tooltip.module.css, packages/react/src/components/Tooltip/Tooltip.stories.tsx, packages/react/src/components/Tooltip/Tooltip.tsx
=> feat(Tooltip): Add inverted version

packages/react/src/components/form/Checkbox/Group/Group.test.tsx, packages/react/src/components/form/Fieldset/Fieldset.mdx, packages/react/src/components/form/Fieldset/Fieldset.test.tsx, packages/react/src/components/form/Fieldset/Fieldset.tsx, packages/react/src/components/form/Radio/Group/Group.test.tsx, packages/react/src/components/form/Search/Search.module.css, packages/react/src/components/form/useFormField.test.tsx
Resolves #1179
Note: This change also effects `Checkbox.Group` and `Radio.Group` which will now require the legend prop to be provided
=> feat(Fieldset): Make legend prop required

packages/css/nativeselect.css, packages/css/search.css, packages/css/textarea.css, packages/css/textfield.css, packages/react/src/components/form/Combobox/Option/Option.module.css, packages/react/src/components/form/NativeSelect/NativeSelect.module.css, packages/react/src/components/form/Search/Search.module.css, packages/react/src/components/form/Textarea/Textarea.module.css, packages/react/src/components/form/Textfield/Textfield.module.css
=> refactor: Changed border-action-dark and -hover to border-input-default and -hover

packages/react/src/components/Button/Button.tsx, packages/react/src/components/Tabs/Tab/Tab.tsx
=> chore: Add deprecation warning for `icon` and `iconPlacement`

packages/react/src/components/Button/Button.module.css, packages/react/src/components/Button/Button.tsx, packages/react/src/components/Tabs/Tab/Tab.module.css, packages/react/src/components/Tabs/Tab/Tab.tsx, packages/react/src/components/Tabs/Tab/useTab.ts
=> chore: Update `icon` css selectors on `Button` and `Tab`

packages/react/src/components/form/NativeSelect/NativeSelect.module.css, packages/react/src/components/form/Search/Search.module.css, packages/react/src/components/form/Textarea/Textarea.module.css, packages/react/src/components/form/Textfield/Textfield.module.css, packages/react/src/components/legacy/LegacyFieldSet/FieldSet.module.css
=> refactor: Update disabled opacity to use correct token

packages/react/src/components/form/Combobox/Combobox.tsx
=> feat(Combobox): Disable looping when navigating list with keyboard

packages/react/src/components/form/Combobox/Combobox.stories.tsx, packages/react/src/components/form/Combobox/internal/ComboboxChips.tsx
=> fix(Combobox): Removing a chip with `enter` selects a value from the list

packages/react/src/components/form/Combobox/internal/ComboboxClearButton.tsx
=> fix(Combobox): Pressing `enter` on clear button does not work

packages/react/src/components/form/Radio/Radio.module.css
testing rem instead of fds-sizing for radio size.
Just made a separate branch from #1331 for testing
=> Stack on #1331

packages/react/src/components/HelpText/HelpText.mdx, packages/react/src/components/HelpText/HelpText.stories.tsx, packages/react/src/components/HelpText/HelpText.tsx
=> feat(HelpText): :sparkles: Add portal support

packages/react/src/components/index.ts
Export new `Table` component made in #1364
=> chore(Table): :sparkles: Export new `Table` component

packages/react/src/components/Modal/Modal.stories.tsx
The story was using the legacy select, updated to use the new combobox
=> docs: Update modal story to use new `Combobox`

packages/react/src/components/form/NativeSelect/NativeSelect.stories.tsx, packages/react/src/components/form/NativeSelect/NativeSelect.test.tsx, packages/react/src/components/form/NativeSelect/NativeSelect.tsx
=> fix(NativeSelect): Fix `readOnly` not disabling element

packages/react/src/components/List/List.tsx, packages/react/src/components/List/ListItem/ListItem.tsx, packages/react/src/components/List/index.ts
List components were missing `forwardRef`
=> feat(List): Add `forwardRef`

packages/react/src/components/form/Combobox/Combobox.module.css
Changed chip and input gap from `spacing-1` to `spacing-2` after feedback
=> style(Combobox): Change chips gap to `spacing-2`

packages/react/src/components/form/Combobox/Combobox.stories.tsx
Update stories after feedback on slack
=> docs(Combobox): Add `maxWidth` and gap between chips

packages/react/src/components/List/List.tsx
Adds support for passing a custom heading id
=> feat(List): Add support for custom heading id

packages/react/src/components/Link/Link.module.css
As part of meeting around about #833 we decided to change focus behaviour for Link
=> refactor(Link): :recycle: Change focus to focus-visible

packages/react/src/components/Pagination/Pagination.tsx
=> fix(Pagination): Add default aria-label to `nav`

packages/react/src/components/Accordion/Accordion.module.css, packages/react/src/components/Accordion/AccordionHeader/AccordionHeader.tsx
=> fix(Accordion): Fix focus style

packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Button/Button.test.tsx, packages/react/src/components/Button/Button.tsx, packages/react/src/components/Card/Card.stories.tsx, packages/react/src/components/DropdownMenu/DropdownMenu.stories.tsx, packages/react/src/components/Modal/ModalHeader/ModalHeader.tsx, packages/react/src/components/Pagination/Pagination.tsx, packages/react/src/components/ToggleGroup/ToggleGroup.stories.tsx, packages/react/src/components/ToggleGroup/ToggleGroupItem/ToggleGroupItem.tsx
=> feat(Button): Change `icon` to boolean and remove `iconPlacement`

packages/react/src/components/Tabs/Tab/Tab.tsx, packages/react/src/components/Tabs/Tab/useTab.ts, packages/react/src/components/Tabs/Tabs.stories.tsx
=> feat(Tabs): Remove `icon` prop

packages/react/src/components/Link/Link.test.tsx, packages/react/src/components/Link/Link.tsx, packages/react/src/types/OverridableComponent.ts
=> chore: Add deprecation warning to `as` property

packages/react/src/components/Typography/Ingress/Ingress.tsx
=> feat(Ingress): Add `asChild` support to `Ingress`

packages/react/src/components/ToggleGroup/ToggleGroupItem/ToggleGroupItem.tsx
=> chore(ToggleGroupItem): Change to use use `asChild`

.storybook/main.ts
Fixes storybook crashing on React undefined
=> chore: Fix Storybook after jsx-runtime changes

.storybook/preview.tsx
=> docs: :bug: Fix rendering of lists in Storybook after component changes

package.json
=> chore: Remove `pack:react`

packages/react/src/components/List/List.test.tsx, packages/react/src/components/List/List.tsx, packages/react/src/components/List/ListHeading.tsx
Fixes after my attempt to simplify code >_<
=> fix(List): :bug: Should correctly set `aria-labelledby`

.stylelintrc.mjs, packages/react/src/components/Typography/Heading/Heading.module.css, packages/react/src/components/Typography/Heading/Heading.tsx
=> feat(Heading): Add two larger sizes

packages/react/src/components/List/List.mdx, packages/react/src/components/Table/Table.stories.tsx, packages/react/src/components/form/Checkbox/Checkbox.mdx, packages/react/src/components/form/Checkbox/Checkbox.module.css, packages/react/src/components/form/Checkbox/Checkbox.stories.tsx, packages/react/src/components/form/Checkbox/Checkbox.tsx
=> feat(Checkbox): Add indeterminate state

apps/storefront/components/SubPages/Banner/Banner.module.css, apps/storefront/components/SubPages/Banner/Banner.tsx, apps/storefront/layouts/MenuPageLayout/MenuPageLayout.tsx, apps/storefront/layouts/NavMenuPageLayout/NavMenuPageLayout.tsx, apps/storefront/layouts/NavPageLayout/NavPageLayout.tsx, apps/storefront/layouts/PageLayout/PageLayout.tsx, apps/storefront/package.json, apps/storefront/pages/god-praksis/index.mdx, apps/storefront/pages/grunnleggende/index.mdx, apps/storefront/pages/monstre/index.mdx, yarn.lock
=> feat(storefront): Add `Banner` component to sub-pages

packages/react/src/components/Modal/Modal.mdx, packages/react/src/components/Modal/Modal.stories.tsx, packages/react/src/components/Modal/Modal.test.tsx, packages/react/src/components/Modal/ModalDialog.tsx, packages/react/src/components/Modal/ModalHeader/ModalHeader.tsx, packages/react/src/components/Modal/ModalRoot.tsx, packages/react/src/components/Modal/ModalTrigger/ModalTrigger.tsx, packages/react/src/components/Modal/index.ts, packages/react/src/components/Modal/useModalState.ts
=> feat(Modal): Add `Modal.Trigger`

packages/react/src/components/form/Combobox/Combobox.tsx, packages/react/src/components/form/Combobox/internal/ComboboxInput.tsx
=> feat(Combobox): Add `forwardRef` to input

packages/react/src/components/Popover/Popover.module.css
=> style(Popover): Remove `max-height`

packages/react/src/components/Modal/ModalContent/ModaContent.tsx, packages/react/src/components/Modal/ModalFooter/ModalFooter.tsx, packages/react/src/components/Modal/ModalHeader/ModalHeader.tsx, packages/react/src/components/Modal/index.ts
=> feat(Modal): Make sub-components composable

packages/react/src/components/form/Combobox/Combobox.mdx, packages/react/src/components/form/Combobox/Combobox.module.css, packages/react/src/components/form/Combobox/Combobox.stories.tsx, packages/react/src/components/form/Combobox/Combobox.test.tsx, packages/react/src/components/form/Combobox/Combobox.tsx
=> feat(Combobox): Add loading state

packages/react/src/components/HelpText/HelpText.module.css, packages/react/src/components/HelpText/HelpText.tsx
=> fix(HelpText): :bug: Focus and hover should now be correct

.storybook/preview.tsx
=> chore(storybook): Add `className='sb-unstyled'` to own components

apps/storefront/components/NavigationCard/NavigationCard.module.css
=> feat(storefront): Update `NavigationCard` design

packages/react/src/components/Popover/Popover.mdx, packages/react/src/components/Popover/Popover.stories.tsx, packages/react/src/components/Popover/Popover.test.tsx, packages/react/src/components/Popover/Popover.tsx, packages/react/src/components/Popover/PopoverContent.tsx, packages/react/src/components/Popover/PopoverTrigger.tsx
=> fix(Popover): Update aria attributes

apps/storefront/components/Tokens/TokenList/TokenList.module.css, apps/storefront/components/Tokens/TokenList/TokenList.tsx, apps/storefront/package.json, apps/storefront/pages/_app.tsx, yarn.lock
This removes `@navikt/ds-css` and `@navikt/ds-react`
=> chore(storefront): Use own `DropdownMenu`

packages/react/src/components/form/Combobox/Combobox.tsx
=> docs(combobox): Update JSDoc

docs-components/DoAndDont/DoAndDont.module.css
=> style(DoAndDont): Align images left

apps/storefront/pages/grunnleggende/designelementer/typografi.mdx
=> docs(storefront): Update typography page

apps/storefront/layouts/BlogArticleLayout/BlogArticleLayout.module.css, apps/storefront/pages/bloggen/dette-er-eit-navn.mdx
=> fix(storefront): Center image in figure

apps/storefront/components/Banner/Banner.module.css, apps/storefront/components/Header/Header.module.css, apps/storefront/components/MdxContent/MdxContent.module.css, apps/storefront/components/SidebarMenu/SidebarMenu.module.css, apps/storefront/layouts/BlogArticleLayout/BlogArticleLayout.tsx, apps/storefront/layouts/MenuPageLayout/MenuPageLayout.module.css, apps/storefront/layouts/MenuPageLayout/MenuPageLayout.tsx, apps/storefront/layouts/NavMenuPageLayout/NavMenuPageLayout.module.css, apps/storefront/pages/bloggen/index.mdx, apps/storefront/pages/god-praksis/index.mdx, apps/storefront/pages/grunnleggende/designelementer/design-tokens.mdx, apps/storefront/pages/grunnleggende/designelementer/farger.mdx, apps/storefront/pages/grunnleggende/designelementer/ikoner.mdx, apps/storefront/pages/grunnleggende/designelementer/skygger.mdx, apps/storefront/pages/grunnleggende/designelementer/storrelser-og-avstander.mdx, apps/storefront/pages/grunnleggende/designelementer/typografi.mdx, apps/storefront/pages/grunnleggende/for-designere/bidra-i-figma.mdx, apps/storefront/pages/grunnleggende/for-designere/kom-i-gang.mdx, apps/storefront/pages/grunnleggende/for-utviklere/kom-i-gang.mdx, apps/storefront/pages/grunnleggende/for-utviklere/komposisjon.mdx, apps/storefront/pages/grunnleggende/index.mdx, apps/storefront/pages/grunnleggende/introduksjon/designprinsipper.mdx, apps/storefront/pages/grunnleggende/introduksjon/om-designsystemet.mdx, apps/storefront/pages/grunnleggende/introduksjon/slack.mdx, apps/storefront/pages/grunnleggende/introduksjon/tilgjengelighet.mdx, apps/storefront/pages/grunnleggende/introduksjon/verdier.mdx, apps/storefront/pages/monstre/index.mdx
=> feat(storefront): Style Menypage Layout, Sidebar and Header

packages/react/src/components/Table/Table.module.css
=> style(TableCell): Add background color

packages/css/react-css-modules.css, packages/react/src/components/Tabs/Tab/Tab.module.css, packages/react/src/components/Tabs/Tabs.mdx, packages/react/src/components/Tabs/Tabs.stories.tsx
=> feat(Tabs)!: Remove icon sizing

packages/react/src/components/form/Combobox/Combobox.stories.tsx, packages/react/src/components/form/Combobox/Combobox.tsx, packages/react/src/components/form/Combobox/useCombobox.test.tsx, packages/react/src/components/form/Combobox/useCombobox.tsx
=> feat(Combobox): Add `initialValue` prop

apps/storefront/layouts/ComponentsLayout/ComponentsLayout.tsx
https://metatags.io/?url=https%3A%2F%2Fstorefront-pr-1733.dev.designsystemet.no%2Fkomponenter
=> fix(storefront): Add meta title and description to Komponenter

.storybook/manager-head.html
Updates header in storybook to look the same as on the storefront
=> chore(storybook): Update header

.storybook/preview.tsx, packages/css/postcss-layers.js, packages/css/postcss.config.js, packages/react/scripts/generate-css.ts
Not permanent solution until we can do layers for each component, which will be done after #1696.
Related to #1456
Read more about cascade layers: https://css-tricks.com/css-cascade-layers/
=> feat(css): Add css layers

apps/storefront/pages/grunnleggende/for-designere/kom-i-gang.mdx
=> chore(storefront): Update link to icon library

packages/react/src/components/form/Checkbox/Checkbox.module.css, packages/react/src/components/form/Checkbox/Checkbox.tsx
New styling that changed the label::before into input::before
Fixes #1740
=> fix(Checkbox): Remove empty label element

packages/css/react-css-modules.css, packages/react/src/components/form/Checkbox/Checkbox.module.css
When reviewing #1737 I noticed some ways we could fix unwanted spacing and further optimize existing css.
Fixed the empty spacing around:
=> fix(Checkbox): :bug: Removed unwanted spacing when no label is defined

packages/react/src/components/form/Radio/Radio.module.css, packages/react/src/components/form/Radio/Radio.tsx
Changed to use input instead of label::before for styling
This should fix #1741
=> fix(Radio): Remove empty label element (#1741)

packages/css/react-css-modules.css, packages/react/src/components/form/Radio/Radio.module.css
Applying same changes as in #1762 to keep in sync with `Checkbox`
=> fix(Radio): :bug: Removed unwanted spacing when no label is defined

apps/storefront/pages/index.mdx
=> docs: fix link to components

apps/storefront/tokens/altinn.ts, apps/storefront/tokens/brreg.ts, apps/storefront/tokens/digdir.ts, apps/storefront/tokens/tilsynet.ts, design-tokens/Base/Semantic.json, packages/theme/brand/altinn/tokens.css, packages/theme/brand/brreg/tokens.css, packages/theme/brand/digdir/tokens.css, packages/theme/brand/tilsynet/tokens.css
=> feat(Ingress): Change line height

packages/css/react-css-modules.css, packages/react/src/components/Pagination/Pagination.module.css
=> style(Pagination): Adjust spacing on compact

packages/css/react-css-modules.css, packages/react/src/components/Chip/Chip.module.css, packages/react/src/components/Chip/Removable/Removable.stories.tsx
=> style(Chip): New colors and spacing

apps/storefront/layouts/PageLayout/PageLayout.module.css
=> fix(storefront): Wrap author and date on `PageLayout`

.github/DISCUSSION_TEMPLATE/Components.yml
Added a template for creating a discussion element in the component category.
=> docs: Create Components discussion template

packages/css/react-css-modules.css, packages/react/src/components/form/Switch/Switch.module.css
=> style(Switch): :lipstick: Adjust hover padding

packages/css/index.css, packages/css/react-css-modules.css, packages/css/skiplink.css, packages/css/utils.css, packages/react/src/components/SkipLink/SkipLink.test.tsx, packages/react/src/components/SkipLink/SkipLink.tsx
=> fix(Skiplink): :bug: Should now show correctly

package.json, packages/react/src/components/Button/Button.tsx, yarn.lock
- Updated `clsx` to get `clsx/lite`
- Replaced use in `Button` to test it was working correctly
=> refactor(Button): :recycle: Replace `clsx` with `clsx/lite`

packages/react/src/components/Typography/Paragraph/Paragraph.tsx
=> feat(Paragraph): Remove deprectated `short` prop

packages/css/ingress.css, packages/react/src/components/Typography/Ingress/Ingress.tsx
=> chore(Ingress): Add layer namespace

apps/storefront/components/ClipboardBtn/ClipboardBtn.tsx, apps/storefront/components/Tokens/TokenColor/TokenColor.module.css, apps/storefront/components/Tokens/TokenList/TokenList.module.css, apps/storefront/components/Tokens/TokenList/TokenList.tsx
Small styling fix to reduce spacing between the token name and value on this page: https://www.designsystemet.no/grunnleggende/designelementer/farger
=> chore(storefront): Fix styling of TokenList

packages/css/divider.css, packages/css/index.css, packages/react/src/components/Divider/Divider.tsx
=> refactor(Divider): ♻️ Move styling to `divider.css`

packages/css/error-summary.css, packages/css/index.css, packages/react/src/components/ErrorSummary/ErrorSummaryRoot.tsx
=> chore(ErrorSummary): :recycle: Move styling to `error-summary.css`

packages/react/src/components/form/Combobox/Combobox.test.tsx, packages/react/src/components/form/Combobox/Combobox.tsx, packages/react/src/components/form/Combobox/useCombobox.tsx
Resolves #1982
Also added a test for this, so it does not happen in the future
=> fix(Combobox): Show all options in single mode when a value is selected

apps/storefront/components/Image/Image.module.css
=> fix(Image): make `boxShadow` only apply to image

packages/css/paragraph.css, packages/react/src/components/Typography/Paragraph/Paragraph.stories.tsx, packages/react/src/components/Typography/Paragraph/Paragraph.tsx
=> feat(Paragraph): add shorthand sizes

packages/css/heading.css, packages/react/src/components/Typography/Heading/Heading.stories.tsx, packages/react/src/components/Typography/Heading/Heading.tsx
=> feat(Heading): add shorthand sizes

packages/css/label.css, packages/react/src/components/Typography/Label/Label.stories.tsx, packages/react/src/components/Typography/Label/Label.tsx
=> feat(Label): add shorthand sizes

packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Spinner/Spinner.stories.tsx, packages/react/src/components/Spinner/Spinner.tsx, packages/react/src/components/form/Combobox/Combobox.tsx
=> feat(Spinner): add shorthand sizes

packages/css/error-message.css, packages/react/src/components/Typography/ErrorMessage/ErrorMessage.stories.tsx, packages/react/src/components/Typography/ErrorMessage/ErrorMessage.tsx
=> feat(ErrorMessage): add shorthand sizes

packages/css/textfield.css, packages/react/src/components/form/CharacterCounter.tsx, packages/react/src/components/form/Textfield/Textfield.stories.tsx, packages/react/src/components/form/Textfield/Textfield.tsx, packages/react/src/components/form/Textfield/useTextfield.ts, packages/react/src/components/form/useFormField.ts
#1981
This breaks other form components, but will be fixed in later PRs
=> feat(Textfield): add shorthand sizes

packages/css/switch.css, packages/react/src/components/form/Switch/Switch.stories.tsx, packages/react/src/components/form/Switch/Switch.tsx
=> feat(Switch): add shorthand sizes

packages/css/search.css, packages/react/src/components/form/Search/Search.stories.tsx, packages/react/src/components/form/Search/Search.tsx, packages/react/src/components/form/Search/useSearch.ts
=> feat(Search): add shorthand sizes

packages/css/checkbox.css, packages/react/src/components/form/Checkbox/Checkbox.stories.tsx, packages/react/src/components/form/Checkbox/Checkbox.tsx
=> feat(Checkbox): add shorthand sizes

packages/css/textarea.css, packages/react/src/components/form/Textarea/Textarea.stories.tsx, packages/react/src/components/form/Textarea/Textarea.tsx, packages/react/src/components/form/Textarea/useTextarea.ts
=> feat(Textarea): add shorthand sizes

packages/css/ingress.css, packages/react/src/components/Typography/Ingress/Ingress.stories.tsx, packages/react/src/components/Typography/Ingress/Ingress.tsx
=> feat(Ingress): add shorthand sizes

packages/css/tag.css, packages/react/src/components/Tag/Tag.stories.tsx, packages/react/src/components/Tag/Tag.tsx
=> feat(Tag): add shorthand sizes

packages/css/table.css, packages/react/src/components/Table/Table.tsx
=> feat(Table): add shorthand sizes

packages/css/helptext.css, packages/react/src/components/HelpText/HelpText.stories.tsx, packages/react/src/components/HelpText/HelpText.tsx
=> feat(HelpText): add shorthand sizes

packages/css/dropdownmenu.css, packages/react/src/components/DropdownMenu/DropdownMenu.stories.tsx, packages/react/src/components/DropdownMenu/DropdownMenu.tsx, packages/react/src/components/DropdownMenu/DropdownMenuContent.tsx, packages/react/src/components/DropdownMenu/DropdownMenuItem.tsx
=> feat(DropdownMenu): add shorthand sizes

packages/react/src/components/ToggleGroup/ToggleGroup.tsx, packages/react/src/components/ToggleGroup/ToggleGroupItem/useToggleGroupitem.ts
=> feat(ToggleGroup): add shorthand sizes

packages/css/tabs.css, packages/react/src/components/Tabs/Tabs.mdx, packages/react/src/components/Tabs/Tabs.stories.tsx, packages/react/src/components/Tabs/Tabs.tsx
=> feat(Tabs): add shorthand sizes

packages/css/native-select.css, packages/react/src/components/form/NativeSelect/NativeSelect.stories.tsx, packages/react/src/components/form/NativeSelect/NativeSelect.tsx, packages/react/src/components/form/NativeSelect/useNativeSelect.ts
=> feat(NativeSelect): add shorthand sizes

packages/css/pagination.css, packages/react/src/components/Pagination/Pagination.stories.tsx, packages/react/src/components/Pagination/Pagination.tsx, packages/react/src/components/Pagination/PaginationRoot.tsx
=> feat(Pagination): add shorthand sizes

packages/css/index.css
=> chore: sort `fds.box` layer

packages/react/src/components/Tabs/Tabs.tsx
=> fix(Tabs): `className` being overridden

packages/css/radio.css
=> fix(RadioGroup): bigger horizontal gap between inputs

packages/react/src/components/Tooltip/Tooltip.tsx
=> fix(Tooltip): rendered in a portal by default

packages/react/src/components/form/Textfield/Textfield.tsx
=> fix(Textfield): character counter inital value

.changeset/quiet-mangos-cry.md, packages/react/src/components/Divider/Divider.tsx
- Hide Divider from screen readers as they only cause distraction
=> fix(Divider): hide from screen readers

packages/react/src/components/Button/Button.mdx, packages/react/src/components/Button/Button.stories.tsx
=> docs: button stories english

packages/css/modal.css
uses correct design from Figma
=> style(Modal): use --ds-border-radius-lg

.changeset/four-pears-tie.md, packages/css/checkbox.css, packages/css/fieldset.css, packages/css/radio.css, packages/react/src/components/form/Checkbox/Group/Group.tsx, packages/react/src/components/form/Radio/Group/Group.tsx
=> fix: same spacing in checkbox and radio groups

.changeset/brave-months-sleep.md, packages/react/src/components/Modal/index.ts
- Modal was missing export for `ModalRoot`
=> fix(Modal): export moodalroot

biome.jsonc, packages/cli/src/tokens/formats/css.ts, packages/react/src/components/Table/Table.stories.tsx
=> chore: enable `noAccumulatingSpread` in biome

.changeset/chatty-cheetahs-fetch.md, packages/css/skiplink.css
=> style(SkipLink): restyle skiplink to look like link

packages/css/error-summary.css, packages/css/package.json, packages/css/postcss.config.js, yarn.lock
- Fixes #2257
- Nested one file to check everything works as expected :)
=> chore: support css nesting

packages/css/badge.css
fixes some descrepancies between figma and code
=> style(Badge): :art: correct sizing and padding

.changeset/few-brooms-confess.md, .changeset/fifty-buses-beam.md, packages/css/table.css, packages/react/src/components/Table/Table.stories.tsx, packages/react/src/components/Table/Table.tsx
=> chore(Table): css changes to hover and width

packages/react/src/components/Table/Table.mdx, packages/react/src/components/Table/Table.stories.tsx
=> docs(Table): write documentation and guidelines

apps/theme/app/globals.css
=> chore: fix padding on header in theme

apps/storefront/app/bloggen/_components/PostLayout/PostLayout.module.css, apps/storefront/app/bloggen/_components/PostLayout/PostLayout.tsx, apps/storefront/app/layout.tsx
sets the `metadataBase` so it is not always using localhost.
fixes width on blog header images
=> chore(storefront): metadata and blog image fixes

apps/storefront/app/(frontpage)/layout.module.css, apps/storefront/app/(frontpage)/layout.tsx, apps/storefront/app/layout.tsx, apps/storefront/components/VersionBanner/VersionBanner.module.css, apps/storefront/components/VersionBanner/VersionBanner.tsx, apps/storefront/components/index.ts
=> chore(storefront): add banner about version on next site

packages/react/src/components/ErrorSummary/ErrorSummary.mdx, packages/react/src/components/ErrorSummary/ErrorSummary.stories.tsx
=> docs(ErrorSummary): write documentation and guidelines

.changeset/witty-moons-sleep.md, packages/react/package.json, yarn.lock
=> fix(Combobox): fix virtual items having big gap

.changeset/metal-bananas-notice.md, packages/css/switch.css
=> fix(Switch): don't show check when not checked in readonly

packages/react/src/components/form/Textfield/Textfield.mdx, packages/react/src/components/form/Textfield/Textfield.stories.tsx
resolves #2299
Also removed full width story, as this was not adding anything useful to the docs
=> docs(Textfield): better prefix and suffix story

.changeset/mean-ducks-argue.md, packages/css/tooltip.css
=> feat(tooltip): remove css variables

.changeset/stupid-tables-applaud.md, packages/css/tag.css, packages/react/src/components/Tag/Tag.tsx
Part of #2295 
Not fixing accessibility/wrapping/display:flex in this PR as this will be part of work after #2355
=> fix(Tag): css adjustments

.changeset/flat-experts-drop.md, packages/css/error-summary.css, packages/react/src/components/ErrorSummary/ErrorSummary.mdx, packages/react/src/components/ErrorSummary/ErrorSummary.stories.tsx, packages/react/src/components/ErrorSummary/ErrorSummary.tsx, packages/react/src/components/ErrorSummary/ErrorSummaryHeading.tsx, packages/react/src/components/ErrorSummary/ErrorSummaryList.tsx, packages/react/src/components/ErrorSummary/index.ts
Part of https://github.com/digdir/designsystemet/issues/2295 and https://github.com/digdir/designsystemet/issues/2221
=> fix(ErrorSummary): css and api alignments

.changeset/clever-cobras-rescue.md, packages/css/textarea.css, packages/react/src/components/form/Textarea/Textarea.stories.tsx
implementing as dicussed in meeting 2024.09.19
=> style(textarea): use new field-sizing: content

apps/storefront/components/Footer/Footer.tsx
ref discussion on Slack about colors and section with logos
=> chore: temp no Udir logo

.changeset/lemon-countries-smoke.md, packages/css/baseline/typography.css
=> fix(heading): make md heading work

apps/storefront/app/not-found.tsx, apps/storefront/mdx-components.tsx, apps/storybook/.storybook/preview.tsx, apps/storybook/docs-components/DoAndDont/DoAndDont.tsx, apps/storybook/docs-components/Information/Information.tsx, apps/theme/components/Previews/Components/Components.tsx, apps/theme/components/TokenModal/TokenModal.tsx, packages/css/baseline/typography.css, packages/css/error-summary.css, packages/css/utilities.css, packages/react/src/components/Alert/Alert.stories.tsx, packages/react/src/components/ErrorSummary/ErrorSummaryHeading.tsx, packages/react/src/components/List/List.stories.tsx, packages/react/src/components/Modal/Modal.stories.tsx, packages/react/src/components/Typography/Heading/Heading.stories.tsx, packages/react/src/components/Typography/Heading/Heading.tsx, packages/react/src/components/Typography/Label/Label.stories.tsx, packages/react/src/components/Typography/Label/Label.tsx, packages/react/src/components/Typography/Paragraph/Paragraph.stories.tsx, packages/react/src/components/Typography/Paragraph/Paragraph.tsx, packages/react/src/components/Typography/Typography.stories.tsx, packages/react/src/components/Typography/ValidationMessage/ValidationMessage.stories.tsx, packages/react/src/components/Typography/ValidationMessage/ValidationMessage.tsx, packages/react/src/components/form/Checkbox/CheckboxGroup.stories.tsx, packages/react/src/components/form/Combobox/Combobox.stories.tsx, packages/react/src/components/form/Radio/RadioGroup.stories.tsx, packages/react/src/components/form/Search/Search.stories.tsx, packages/react/stories/showcase.stories.tsx
=> feat: remove spacing on typography

.changeset/cyan-adults-roll.md, packages/css/skiplink.css, packages/react/src/components/SkipLink/SkipLink.stories.tsx, packages/react/src/components/SkipLink/SkipLink.tsx
=> chore(skiplink): simplify DOM

packages/css/breadcrumbs.css
=> fix(Breadcrumbs): back only bug

packages/react/src/components/Accordion/AccordionHeading.tsx, packages/react/src/components/Accordion/AccordionItem.tsx
Fixes typo in docs https://designsystemet.slack.com/archives/C05RF86A3K7/p1728035315902779
=> docs(Accordion): fix typo

.github/workflows/test.yml, .github/workflows/visual-tests.yml
This allows Chromatic to set the new baseline for main/next branches
=> ci: move Chromatic to separate workflow and also run it after PR is merged

apps/theme/components/ColorPicker/ColorPicker.tsx, apps/theme/components/ThemeToolbar/ThemeToolbar.module.css, apps/theme/components/ThemeToolbar/ThemeToolbar.tsx
Fixes rendering of select in theme builder
=> fix(Theme): select styling

.changeset/orange-months-listen.md, packages/css/button.css, packages/css/dropdown.css
=> style(button): use weight 500

apps/storefront/components/MdxContent/MdxContent.module.css
unspotted style issue when storefront PR was merged.
Also fixes code tags not being styled when nested, for eample in a list
=> chore: fix max-width on content

README.md
=> chore: update reeadme with chromatic

packages/css/popover.css, packages/react/src/components/Popover/Popover.tsx
resolves #2657
This only solves it for popover, since tooltip does not have pseudo element yet, Will solve this for tooltip in #2656
=> feat(popover): adhere to arrow size in gap

packages/css/input.css
As pointed out by hawk-eye @mimarz 💪 🙏 🦅 
https://designsystemet.slack.com/archives/C07K7NEKXEW/p1729843841118129
=> fix(Input): inherit line-height

apps/storybook/.storybook/manager-head.html, packages/react/stories/showcase.module.css, packages/react/stories/showcase.stories.tsx
fixes #2690
Any suggestions on labeling for the `ToggleGroup`?
=> docs: :memo: Add Designsystemet data attr controls to Showcase in Storybook

packages/css/input.css
=> fix(Input): checkbox rendering

.changeset/five-pens-accept.md, packages/react/src/components/Dropdown/Dropdown.stories.tsx, packages/react/src/components/Popover/Popover.test.tsx, packages/react/src/components/Popover/Popover.tsx
=> fix(Popover): controlled with svg bug

packages/css/input.css
- Fixes https://designsystemet.slack.com/archives/C07K7NEKXEW/p1730362755452699
=> fix(Input): focus alignment

.github/workflows/checks.yml, plugins/figma/src/ui/app.tsx, plugins/figma/src/ui/components/Footer/Footer.tsx, plugins/figma/src/ui/pages/Theme/Theme.tsx, plugins/figma/src/ui/pages/Themes/Themes.tsx
We will make a separate PR where we can typecheck everything at once in one workflow.
=> chore(figma-plugin): use `data-size`

packages/css/input.css
Fixes https://designsystemet.slack.com/archives/C07JH3RJVPG/p1730808962749429
=> fix(Input): use border-strong for invalid

packages/css/field.css, packages/react/src/components/form/Field/Field.stories.tsx, packages/react/src/components/form/Field/FieldAffix.tsx
=> chore(Field.Affix): fix styling with single

apps/theme/components/Previews/Components/Components.tsx
- fix a missed update of `Search` after new component api was introduced. 
- fix renegade search and replace for `data-data-size`
=> fix: 💚 Update theme preview with new `Search` component api

.changeset/twenty-cheetahs-leave.md, packages/css/table.css, packages/react/src/components/Table/Table.stories.tsx, packages/react/src/components/Table/Table.test.tsx, packages/react/src/components/Table/TableFoot.tsx, packages/react/src/components/Table/index.ts
=> feat(Table): new `Table.Foot` and style caption

.changeset/old-melons-stare.md, packages/css/table.css
=> chore(table): add z-index to header when sticky

.changeset/sweet-dolphins-hang.md, packages/css/field.css, packages/css/input.css, packages/react/src/components/form/Field/Field.mdx, packages/react/src/components/form/Field/Field.stories.tsx, packages/react/src/components/form/Field/FieldAffix.tsx, packages/react/src/components/form/Field/index.ts, packages/react/src/components/form/Textfield/Textfield.mdx, packages/react/src/components/form/Textfield/Textfield.stories.tsx, packages/react/src/components/form/Textfield/Textfield.tsx
Adjustments found while doing the canceled #2771
=> fix(Field.Affix): make more robust

packages/css/src/alert.css, packages/css/src/card.css, packages/css/src/link.css, packages/css/src/tag.css, packages/react/tsconfig.lib.json, vite.config.ts
This is a sync I did with tokens from figma to code.
These were the only dispcrepancies I could find.
=> style: make sure everything is synced with figma

packages/css/src/avatar.css, packages/css/src/badge.css, packages/css/src/breadcrumbs.css, packages/css/src/button.css, packages/css/src/card.css, packages/css/src/chip.css, packages/css/src/details.css, packages/css/src/dropdown.css, packages/css/src/link.css, packages/css/src/popover.css, packages/css/src/tag.css, packages/css/src/togglegroup.css, packages/react/src/components/Card/Card.stories.tsx, packages/react/src/components/HelpText/HelpText.tsx, packages/react/src/components/Popover/Popover.mdx, packages/react/src/components/Popover/Popover.stories.tsx, packages/react/src/components/Popover/Popover.tsx
=> refactor: :recycle: Adjust `data-color` cascading

packages/css/src/button.css
=> fix(Button): remove redundant token

.changeset/odd-oranges-yell.md, packages/css/src/validation-message.css, packages/react/src/components/ValidationMessage/ValidationMessage.stories.tsx, packages/react/src/components/ValidationMessage/ValidationMessage.tsx, packages/react/src/components/form/Field/FieldCounter.tsx, packages/react/stories/Typography.mdx
=> feat(ValidationMessage): support all severity colors

.changeset/green-plums-scream.md, packages/react/src/components/Field/FieldCounter.tsx, packages/react/src/components/Field/fieldObserver.ts
- Fixes so `Field.Counter` runs on initial mount, [see Slack](https://designsystemet.slack.com/archives/C05RK9VEGJ0/p1734348040273519)
=> fix(Field.Counter): support default value

apps/storefront/app/bloggen/2024/v1rc1/page.mdx, apps/storefront/app/monstre/systemvarsler/page.mdx, apps/storefront/package.json, package.json, yarn.lock
Steamlines use of `CodeSnippet` on the storefront.
Makes sure `next-sitemap` is in the correct package.json
=> fix(storefront): use CodeSnippet and move sitemap pkg

design-tokens/$themes.json, packages/cli/src/tokens/write/generate$themes.ts
Tiny change to order of size sets so that the default size is medium in Figma.
=> chore: changed order on size sets

packages/cli/src/tokens/write.ts
=> fix(cli): :bug: fix base border radius not being set for token create

.changeset/olive-windows-share.md, apps/storybook/.storybook/preview-head.html, apps/storybook/stories/showcase.stories.tsx, packages/cli/src/tokens/build/configs.ts, packages/react/stories/bruk.mdx, packages/theme/brand/altinn.css, packages/theme/brand/altinn/typography/primary.css, packages/theme/brand/altinn/typography/secondary.css, packages/theme/brand/digdir.css, packages/theme/brand/digdir/typography/primary.css, packages/theme/brand/digdir/typography/secondary.css, packages/theme/brand/portal.css, packages/theme/brand/portal/typography/primary.css, packages/theme/brand/portal/typography/secondary.css, packages/theme/brand/uutilsynet.css, packages/theme/brand/uutilsynet/typography/primary.css, packages/theme/brand/uutilsynet/typography/secondary.css, plugins/figma/src/ui/theme.css
=> feat: rename `data-ds-typography` to `data-typography`

.changeset/eighty-cougars-relax.md, .changeset/nasty-monkeys-care.md, packages/react/src/components/Chip/Chips.tsx, packages/react/src/components/Input/Input.stories.tsx, packages/react/src/components/Input/Input.tsx, packages/react/src/components/Switch/Switch.tsx, packages/react/src/components/Textfield/Textfield.stories.tsx, packages/react/src/components/Textfield/Textfield.tsx
=> feat(Input, Textfield): whitelist for `type`

.changeset/few-brooms-draw.md, design-tokens/semantic/style.json, design-tokens/themes/theme.json, design-tokens/themes/theme2.json, design-tokens/themes/theme3.json, design-tokens/themes/theme4.json, packages/cli/src/tokens/design-tokens/default/semantic/style.json, packages/cli/src/tokens/design-tokens/template/themes/theme-base-file.json
=> chore: swapped type from borderRadius -> dimension

.changeset/lovely-turtles-cheer.md, packages/css/src/tabs.css
=> style: add overflow-x scroll to tablist

.changeset/clever-files-fix.md, apps/theme/components/TokenModal/TokenModal.tsx, packages/cli/bin/config.ts, packages/cli/package.json, packages/cli/src/tokens/build.ts, packages/cli/src/tokens/build/types.ts, yarn.lock
resolves #3003 
resolves [#2988](https://github.com/digdir/designsystemet/issues/2988)
=> fix(cli): :bug: Create & build tokens correctly if `support-color` is missing

.changeset/chilled-badgers-jog.md, packages/css/src/chip.css
=> style(Chip): make radio and checbox smaller

.changeset/fast-months-compare.md, packages/css/src/togglegroup.css
=> style: button size in togglegroup

packages/cli/src/migrations/codemods/css/plugins.ts, packages/css/src/suggestion.css
- fixed css variable in `Suggestion` we missed.
- Removed migrated variables count log as it didnt work
=> fix: outdated css variables

.changeset/gorgeous-rockets-jam.md, .changeset/light-avocados-flow.md, packages/css/src/button.css, packages/react/src/components/Button/Button.tsx
reported on slack: https://designsystemet.slack.com/archives/C05RK9VEGJ0/p1738225466761249
=> fix(Button): make spinner scale, correct `loading` type

.changeset/yellow-days-talk.md, packages/css/src/button.css, packages/css/src/card.css
adds custom property for card block
fix variable in button
=> fix: css properties in card, button

.changeset/proud-dogs-ring.md, packages/css/src/breadcrumbs.css
Breadcrumbs: Prevent shrinking chevron
=> fix(Breadcrumbs): prevent shrinking chevron

packages/css/src/chip.css
=> style(Chip.Checkbox): use small border radius

.changeset/beige-eggs-sip.md, packages/css/src/details.css
=> chore(Details): add var for summary color and change vars

packages/react/src/components/Dropdown/Dropdown.stories.tsx
Better shows how this is useful
=> chore: update dropdown controlled story

.changeset/stale-flowers-count.md, packages/css/src/table.css
=> style(Table): background colors on th

packages/react/src/components/Combobox/Combobox.stories.tsx, packages/react/src/components/Suggestion/Suggestion.stories.tsx
Added a folder at the bottom of "Komponenter" in storybook for deprecated components.
=> docs: new folder for deprecated components

.changeset/hip-papayas-decide.md, packages/css/src/dropdown.css
=> style(Dropdown): change background to surface

.changeset/three-humans-poke.md, packages/css/src/dialog.css
=> style(Dialog): change background to surface

.changeset/gold-lemons-fry.md, packages/css/src/dropdown.css, packages/css/src/popover.css
=> style(Popover): change background and add shadow

.changeset/hungry-singers-fry.md, apps/theme/components/OverviewComponents/TableCard/TableCard.tsx, apps/theme/components/Sidebar/ColorPane/ColorPane.tsx, packages/cli/bin/config.ts, packages/cli/src/colors/theme.ts
=> feat(cli, themebuilder): invalidate systemcolors as name for color

.changeset/eleven-hounds-mix.md, .changeset/fast-years-push.md, packages/css/src/button.css, packages/react/src/components/Button/Button.mdx, packages/react/src/components/Button/Button.tsx
=> feat(Button): `loading` sets `aria-disabled`

apps/_components/src/ClipboardButton/ClipboardButton.tsx, apps/_components/src/CodeSnippet/CodeSnippet.tsx, apps/storefront/app/(frontpage)/layout.tsx, apps/storefront/app/(frontpage)/page.mdx, apps/storefront/app/bloggen/(frontpage)/layout.tsx, apps/storefront/app/bloggen/(frontpage)/page.mdx, apps/storefront/app/god-praksis/page.mdx, apps/storefront/components/Banner/Banner.tsx, apps/storefront/components/GithubLink/GithubLink.tsx, apps/storefront/components/NavigationCard/NavigationCard.tsx
=> chore(storefront): add aria-hidden='true' to decorative icons

.github/workflows/deploy-storefront.yml, .github/workflows/deploy-storybook.yml, .github/workflows/deploy-theme.yml, .vscode/settings.json
Previously they didn't select `production` correctly.
Must still be run manually when we release new version to `latest` and merge changes to `main`
=> chore: fix Vercel deploy action environments

.changeset/good-melons-report.md, packages/css/src/input.css, packages/react/src/components/Radio/Radio.stories.tsx
=> style(Radio): fix filled error state in `Fieldset`

packages/cli/README.md, packages/cli/bin/designsystemet.ts
=> docs(cli): add more thorough usage documentation to CLI README

.changeset/quick-loops-send.md, packages/cli/bin/designsystemet.ts, packages/cli/bin/options.ts
=> fix(cli): supplied options were being overridden with default values

packages/react/src/components/Radio/Radio.stories.tsx
Its confusing having a story with validation error but no option "selected" that would trigger said validation error
=> docs(radio): sjokolade

.changeset/loud-trees-swim.md
> 🎉 Version 1.0 of Designsystemet! 🎉
>  
> We are excited to announce the release of Version 1.0 of Designsystemet! This marks a significant milestone as we establish a solid foundation for future development. 🚀
>
=> chore: release v1 changeset

apps/storefront/app/layout.tsx, apps/storefront/utils/is-production.ts, apps/theme/components/TokenModal/TokenModal.tsx, apps/theme/utils/is-production.ts
fixes #3292 
Created a new custom environment variable in Vercel for our apps there, mimicking ENV_VERCEL (as its not working atm)
`DESIGNSYSTEMET_ENV` 
- Production: `production`
- Preview, Development: `preview`
=> chore: add env variables for apps

README.md, packages/css/README.md, packages/react/README.md, packages/theme/README.md
=> docs: update readmes

apps/theme/components/Colors/Colors.module.css, apps/theme/components/Colors/Colors.tsx, apps/theme/components/Group/Group.module.css, apps/theme/components/Group/Group.tsx, apps/theme/components/Scale/Scale.module.css
=> style(themebuilder): fix colorscale alignment

packages/react/src/components/Details/Details.mdx
related to #3359, since it adds docs about animation not working
=> docs(Details): kjente mangler about animation

apps/_components/src/ColorModal/ColorModal.tsx, apps/theme/app/page.tsx, apps/theme/components/Color/Color.tsx, apps/theme/components/ColorContrasts/ColorContrasts.tsx, apps/theme/components/Group/Group.tsx, apps/theme/components/Scale/Scale.tsx, apps/theme/store.ts
=> chore: clean code in themebuilder

packages/react/src/components/Search/Search.mdx
=> docs: search guideline text

apps/storefront/app/grunnleggende/designelementer/farger/page.mdx, apps/storefront/app/grunnleggende/designelementer/storrelser-og-avstander/page.mdx
I don't think we have a background-hover color :D
=> chore: fix wrong color documentation

renovate.json
We have had bugs introduced in patch/minor releases in our tooling (vitest), so we need more control over how dependencies are managed. 
https://docs.renovatebot.com/configuration-options/#rangestrategy
https://docs.renovatebot.com/dependency-pinning/
=> chore: renovate pin dependencies

.github/workflows/deploy-storefront.yml, .github/workflows/deploy-storybook.yml, .github/workflows/deploy-theme.yml, apps/storefront/app/bloggen/2025/V1/page.mdx, apps/storefront/components/GithubLink/GithubLink.tsx, apps/storybook/.storybook/manager-head.html, apps/www/app/_components/edit-page-on-github/edit-page-on-github.tsx, apps/www/app/content/blog/en/V1.mdx, apps/www/app/content/blog/no/V1.mdx
- remove links to next branches
- prefer use `latest`
=> chore: updates for removal of next branch

packages/react/src/components/Field/Field.mdx, packages/react/src/components/Textfield/Textfield.mdx
resolves #3503 
I dunno, is this explanation good enough?
=> chore(Field): note in storybook about usage

.github/workflows/preview-storefront.yml, .github/workflows/preview-storybook.yml, .github/workflows/preview-theme.yml, .github/workflows/preview-www.yml
remove ignore now that we work towards `main`.
=> ci: fix preview actions

packages/react/src/components/Table/Table.mdx
resolves [#3491](https://github.com/digdir/designsystemet/issues/3491)
Thanks @unekinn @adrianflatner ⭐️
=> docs: improved guidelines for Table

packages/react/src/components/Button/Button.mdx
Improved guidelines by Udir 
Thanks @unekinn!
=> docs: improved guidelines for Button

apps/storybook/docs-components/DoAndDont/DoAndDont.tsx, packages/react/src/components/Checkbox/Checkbox.mdx, packages/react/src/components/Checkbox/Checkbox.stories.tsx, packages/react/src/components/Switch/Switch.mdx
=> docs: improved guidelines for Checkbox

apps/theme/app/themebuilder/_utils/useThemeParams.tsx
=> fix(themebuilder): border-radius valuecheck

apps/www/app/_components/mdx-components/mdx-components.tsx, apps/www/app/_components/video-card/video-card.module.css, apps/www/app/_components/video-card/video-card.tsx, apps/www/app/content/best-practices/en/accessibility/understanding-vision-impairment.mdx, apps/www/app/content/best-practices/no/accessibility/understanding-vision-impairment.mdx, apps/www/app/locales/en.ts, apps/www/app/locales/no.ts
=> chore: add video card

.changeset/pretty-women-find.md, apps/storybook/.storybook/preview.tsx, apps/storybook/story-utils/createHtmlStory.tsx, apps/storybook/story-utils/customStylesDecorator.tsx, apps/storybook/story-utils/withScrollHashBehavior.tsx, packages/css/src/error-summary.css, packages/react/src/components/ErrorSummary/ErrorSummary.mdx, packages/react/src/components/ErrorSummary/ErrorSummary.stories.tsx, packages/react/src/components/ErrorSummary/ErrorSummary.tsx, packages/react/src/components/ErrorSummary/html-examples/show-hide.html
resolves #3417 
I started rewriting the storybook but perhaps i should wait on @unekinn to do this seperately as I am now confusing myself trying out different combinations of what we are recommending.
=> fix(errorsummary): removed `aria-live`, `aria-relevant` and `role`

.github/workflows/deploy-storefront.yml, .github/workflows/deploy-storybook.yml, .github/workflows/deploy-theme.yml, .github/workflows/deploy-www.yml, .github/workflows/preview-storefront.yml, .github/workflows/preview-storybook.yml, .github/workflows/preview-theme.yml, .github/workflows/preview-www.yml, .github/workflows/visual-tests.yml, apps/www/app/content/components.ts
resolves #1086
adds if statements to workflows that only works in they are run in our repo.
Makes it look better for external contributors who creates PRs, and removed unwanted runs of workflows
=> ci: add if checks on repo-only workflows

apps/www/package.json, pnpm-lock.yaml
makes it so we dont need #3631
=> chore: remove unused dependency in www

apps/storefront/app/grunnleggende/introduksjon/om-designsystemet/page.mdx, apps/storefront/public/videos/designsystemet/designsystemet-info-en.vtt, apps/storefront/public/videos/designsystemet/designsystemet-info-no.vtt
added video here https://pr-3633.designsystemet.no/grunnleggende/introduksjon/om-designsystemet
=> chore(storefront): add about video with subs

apps/themebuilder/app/root.tsx, apps/themebuilder/vercel.json, apps/www/app/_components/edit-page-on-github/edit-page-on-github.tsx, apps/www/app/content/blog/en/V1.mdx, apps/www/app/content/blog/no/V1.mdx, apps/www/app/content/fundamentals/en/for-designers/contribute-in-figma.mdx, apps/www/app/content/fundamentals/en/introduction/about-the-design-system.mdx, apps/www/app/content/fundamentals/en/introduction/accessibility.mdx, apps/www/app/content/fundamentals/no/for-designers/contribute-in-figma.mdx, apps/www/app/content/fundamentals/no/introduction/about-the-design-system.mdx, apps/www/app/content/fundamentals/no/introduction/accessibility.mdx, apps/www/app/entry.server.tsx, apps/www/app/root.tsx, apps/www/vercel.json
Fixes broken links.
Fixes edit on github link having the possibility to have `path/.mdx`
Redirects trailing slash URLs
=> chore(www): fix broken links, stop trailing slash

.changeset/tough-swans-admire.md, plugins/figma/package.json, plugins/figma/src/common/dummyTheme.ts, plugins/figma/src/common/store.ts, plugins/figma/src/common/utils.ts, plugins/figma/src/plugin/figma/updateVariables.ts, plugins/figma/src/plugin/plugin.ts, plugins/figma/src/ui/pages/Theme/Theme.tsx
=> chore: plugin uses color names from config

apps/www/app/_components/contributors/contributors.module.css, apps/www/app/_components/image-banner/image-banner.module.css, apps/www/app/_components/image-banner/image-banner.tsx, apps/www/app/locales/en.ts, apps/www/app/locales/no.ts
=> chore(www): add play/pause button to video

apps/themebuilder/app/_components/color-preview/color-preview.tsx
=> fix(themebuilder): neutral color on preview cards

apps/www/app/content/blog/en/fluid-typography.mdx, apps/www/app/content/fundamentals/en/for-designers/contribute-in-figma.mdx, apps/www/app/content/fundamentals/en/for-designers/get-started.mdx, apps/www/app/content/fundamentals/no/for-designers/contribute-in-figma.mdx, apps/www/app/content/patterns/no/external-links.mdx
=> fix(www): more broken links

.changeset/tough-swans-admire.md
Changsets publishing is broken. Test if removing changest for private package fixes this.
=> chore: remove changeset for private package

.github/workflows/deploy-www.yml
=> ci(deploy-www): add `NEXT_PUBLIC_DESIGNSYSTEMET_ENV` env

.changeset/whole-dodos-read.md, apps/storybook/.storybook/customTheme.scss, packages/css/src/avatar.css, packages/css/src/base.css, packages/css/src/heading.css, packages/css/src/input.css
- [ x] I have read the [contribution guidelines](https://github.com/digdir/designsystemet/blob/main/CONTRIBUTING.md)
- [ x] I have added a changeset (run `pnpm changeset` if relevant)
=> fix(css): rounding to 1px correctly

.github/workflows/deploy-www.yml, .github/workflows/preview-www.yml, apps/themebuilder/app/_utils/is-production.server.ts, apps/themebuilder/public/robots.txt, apps/themebuilder/react-router.config.ts, apps/www/public/robots.txt, apps/www/react-router.config.ts
I'm not sure why vercel won't get the correct robots.txt file. But keeping it as default Allow would be best in this case
=> fix: robots file

.changeset/two-books-smash.md, packages/react/src/utilities/hooks/usePagination/usePagination.test.tsx, packages/react/src/utilities/hooks/usePagination/usePagination.ts
=> fix(usePagination): don't send negative pages

apps/www/vite.config.ts
Fixes this error which randomly appears on Vercel giving 500 errors
=> chore(www): fix vercel to many files error

.changeset/soft-forks-hammer.md, packages/react/package.json, packages/react/src/components/suggestion/suggestion.tsx, pnpm-lock.yaml
=> fix(Suggestion): use latest u-combobox to fix controlled suggestion

.changeset/gorgeous-trains-kick.md, packages/css/src/input.css
=> style(select): flip chevron when open

.changeset/clever-snails-jump.md, packages/react/src/components/suggestion/suggestion.stories.tsx, packages/react/src/components/suggestion/suggestion.tsx
=> fix(Suggestion): react 18 strict mode compatibility

.github/workflows/release.yml
Add release for apps to production in release action when [changesets has published packages](https://github.com/dotansimha/changesets-action/tree/v1.5.2/?tab=readme-ov-file#with-publishing).
=> chore: add deploy apps to production in release action

packages/react/src/components/switch/switch.mdx, packages/react/src/components/switch/switch.stories.tsx, packages/react/src/components/tooltip/tooltip.mdx, packages/react/src/components/tooltip/tooltip.stories.tsx
=> docs: switch and tooltip

packages/react/src/components/list/list.mdx, packages/react/src/components/list/list.stories.tsx
=> docs: list improvements

apps/www/app/locales/en.ts
=> docs: add SEO keywords for Google

.changeset/breezy-pumpkins-reflect.md, packages/react/src/components/field/field-observer.ts
=> chore(Field): don't check for hidden elements

.changeset/tastaturnavigasjon-docs.md, packages/react/src/components/checkbox/checkbox.mdx, packages/react/src/components/details/details.mdx, packages/react/src/components/dialog/dialog.mdx, packages/react/src/components/dropdown/dropdown.mdx, packages/react/src/components/popover/popover.mdx, packages/react/src/components/skip-link/skip-link.mdx, packages/react/src/components/switch/switch.mdx, packages/react/src/components/toggle-group/toggle-group.mdx
Adds `### Tastaturnavigasjon` sections to component docs using the same **bullet + `<kbd>`** style as in `tabs.mdx`.
Resolves [#3960](https://github.com/digdir/designsystemet/issues/3960)
Updated components:
- **Dialog:** <kbd>Esc</kbd> closes (focus returns to trigger)
- **Dropdown:** <kbd>Enter</kbd>/<kbd>Space</kbd> open/close, <kbd>Enter</kbd>/<kbd>Space</kbd> select, <kbd>Esc</kbd> closes
- **Popover:** <kbd>Enter</kbd>/<kbd>Space</kbd> open/close, <kbd>Esc</kbd> closes
- **Skip Link:** <kbd>Enter</kbd> follows the link and jumps to target
- **Switch:** <kbd>Space</kbd> toggles
- **Toggle Group:** <kbd data-icon>←</kbd>/<kbd data-icon>→</kbd> navigate (single-select), <kbd>Space</kbd>/<kbd>Enter</kbd> activate/toggle
- **Checkbox:** <kbd>Space</kbd> toggles
- **Details:** …
=> docs(react): add “Tastaturnavigasjon” sections

packages/react/src/components/skip-link/skip-link.mdx, packages/react/src/components/toggle-group/toggle-group.mdx
=> docs: guidelines for `skiplink` and `togglegroup`

apps/themebuilder/package.json, apps/www/package.json, package.json, pnpm-lock.yaml
See https://github.com/remix-run/react-router/pull/14070/files#diff-71ce9b29310e85f4b4370e9b734894ad2126713e83076362b73d88a60378006c
=> chore(www): add override for @mjackson/node-fetch-server

.github/workflows/test-visual.yml, apps/storybook/.storybook/main.ts
see https://www.chromatic.com/docs/github-actions/
=> ci: update chromatic workflow

apps/www/app/content/best-practices/en/accessibility/contrast.mdx, apps/www/app/content/best-practices/en/accessibility/understanding-vision-impairment.mdx, apps/www/app/content/best-practices/no/accessibility/contrast.mdx, apps/www/app/content/best-practices/no/content-work/terms.mdx, apps/www/app/content/blog/en/mattilsynet.mdx, apps/www/app/content/blog/en/v1rc2.mdx, apps/www/app/content/blog/en/why-we-need-a-common-design-system.mdx, apps/www/app/content/blog/no/mattilsynet.mdx, apps/www/app/content/blog/no/v1rc2.mdx, apps/www/app/content/blog/no/why-we-need-a-common-design-system.mdx, apps/www/app/content/fundamentals/en/figma/modes-in-figma.mdx, apps/www/app/content/fundamentals/en/introduction/accessibility.mdx, apps/www/app/content/fundamentals/no/code/get-started.mdx, apps/www/app/content/fundamentals/no/figma/colors-in-figma.mdx, apps/www/app/content/fundamentals/no/figma/modes-in-figma.mdx, apps/www/app/content/fundamentals/no/introduction/collaboration.mdx, apps/www/app/content/fundamentals/no/themebuilder/own-theme.mdx, apps/www/app/content/patterns/en/external-links.mdx, apps/www/app/content/patterns/no/external-links.mdx, packages/react/src/components/badge/badge.mdx, packages/react/src/components/button/button.mdx, packages/react/src/components/card/card.mdx, packages/react/src/components/dialog/dialog.mdx, packages/react/src/components/field/field.mdx, packages/react/src/components/pagination/pagination.mdx, packages/react/src/components/table/table.mdx, packages/react/src/components/textarea/textarea.mdx, packages/react/stories/typography.mdx
This is the result of copy-pasting from AIs like ChatGPT.
=> docs: remove use of em dash

.github/workflows/test-visual.yml
=> ci(visual): change if check

.changeset/shaky-jokes-take.md, packages/react/package.json, pnpm-lock.yaml
=> fix(details): firefox tabstop in details-content

.changeset/unlucky-eyes-look.md, packages/css/src/field.css, packages/react/src/components/field/field.stories.tsx
=> style(Field): make sure select and textarea not on same line as label

apps/themebuilder/app/_components/token-modal/token-modal.module.css
=> style(themebuilder): fix horizontal scroll in dialog

package.json, pnpm-workspace.yaml
=> chore: add pnpm minimumReleaseAge

.changeset/tasty-otters-divide.md, packages/css/src/dropdown.css
=> fix(Dropdown): conform heading styles to figma

.changeset/neat-cycles-jam.md, packages/react/package.json, pnpm-lock.yaml
=> fix(suggestion): update u-combobox to 1.0.2

.github/workflows/azure-deploy-storybook.yml, .github/workflows/azure-deploy-themebuilder.yml, .github/workflows/azure-deploy-www.yml, .github/workflows/azure-preview-cleanup.yml, .github/workflows/preview-comment.yml, .github/workflows/release.yml
=> ci: fix security issues
