digdir/designsystemet

packages/react/src/components/Checkbox/Checkbox.stories.mdx, packages/react/src/components/Checkbox/Checkbox.test.tsx, packages/react/src/components/CheckboxGroup/CheckboxGroup.stories.mdx, packages/react/src/components/RadioButton/RadioButton.stories.mdx, packages/react/src/components/RadioButton/RadioButton.test.tsx, packages/react/src/components/RadioGroup/RadioGroup.stories.mdx, packages/react/src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.module.css, packages/react/src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.tsx
In Altinn Studio, we need to have buttons and input fields inside the labels in preview mode (issue #32). Therefore the labels should not be clickable, to avoid overlapping clickable surfaces in the view.
I have also added descriptions of the `presentation` props in the Storybook files.
=> fix: Presentation mode issues on checkboxes and radio buttons

packages/react/src/components/HelpText/HelpText.stories.mdx, packages/react/src/components/Popover/Popover.stories.mdx, packages/react/src/components/Popover/Popover.test.tsx, packages/react/src/components/Popover/Popover.tsx
Focus will not be shifted to popover content on opening popover using keyboard. Tabbing will not enter popover unless there are interactive elements within the popover content.
=> fix(popover): retain focus on trigger when opening popover

packages/react/src/components/HelpText/HelpText.stories.mdx, packages/react/src/components/HelpText/HelpText.tsx, packages/react/src/components/Popover/Popover.module.css, packages/react/src/components/Popover/Popover.stories.mdx, packages/react/src/components/Popover/Popover.tsx
Use z-index and positioning: absolute instead of portaling to handle layering.
This is done in order to get the screenreader to read the content in the popover, when opened, directly after the trigger-element. The portal worked by appending the content to the end of the dom, which would always be read last.
Also update the docs with better canvases for displaying positioning abilities.
=> fix(popover): popover screen reader ordering

packages/react/src/components/Button/Button.module.css
Moved the `onlyIcon` class further down in the CSS file, so that its `padding` property is not overridden by the one defined for the `quiet` class.
- https://github.com/Altinn/altinn-studio/issues/9691
=> fix(Button): Only icon padding

packages/react/src/components/Select/Select.module.css
Z-index must be larger than the one used on `Tabs`.
=> fix(Select): Set higher z-index on option list

jest.config.js, packages/react/src/components/HelpText/HelpText.test.tsx, test/__mocks__/svg.ts
Fix tests that failed after making title required for HelpText component.
Also add svg mock to fix failing SvgIcon component tests.
=> Fix(help text): add title to helptext tests

packages/react/src/components/Popover/Popover.module.css, packages/react/src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.module.css
Update old figma-token in CheckboxRadioTemplate.
Also fix arrow border color inheritance. Needs to be separate for some reason in order to inherit the popovers border color.
=> fix: update figma-token

packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx
Select component should not throw errors if option list is empty.
=> fix(Select): Accept empty list of options

packages/react/src/components/Popover/Popover.stories.mdx, packages/react/src/components/Popover/Popover.test.tsx
It is not obvious that the popover trigger need to have a `ref`, so I added a couple of sentences about it.
=> docs(Popover): Add note about trigger ref

packages/react/src/components/_InputWrapper/InputWrapper.module.css
Change outline style of inputWrapper to `solid`. The `auto` style was making the ouline-offset calculate distance from the div and not the divs border.
Old:
New:
=> fix(InputWrapper): Change outline style to solid from auto to make outline-offset work

packages/react/src/components/Accordion/Accordion.stories.mdx, packages/react/src/components/Accordion/AccordionHeader.module.css, packages/react/src/components/Accordion/AccordionHeader.tsx
Fixed some errors that appeared when moving the component.
- The `subtitle` class should be two different classes; `subtitle` and `withSubtitle`.
- The subtitle wrapper was changed from `div` to `span` because it was inside a button. This made it appear at the same line as the main title, while it should appear below it. Fixed by setting `display: inline-flex` on the `title` class.
=> fix(Accordion): Fix subtitle placement issues

docs-components/ComponentUsage/ComponentUsage.tsx, packages/react/src/components/Button/Button.module.css, packages/react/src/components/Button/Button.stories.mdx
Added `width` property to `onlyIcon` class, along with better CSS organization and some additional examples in the docs.
=> fix(Button): Enforce icon button to have same width and height

.storybook/main.js, package.json, yarn.lock
Added CSS modules addon to make class names of components recognizable when they are rendered in Storybook. This makes debugging easier.
=> chore: Add CSS modules addon to Storybook

packages/react/src/components/Popover/Popover.module.css
We have a dependency in our project that sets the default `box-sizing` for all divs to `border-box`. 
This ensures that the arrow of the popover has `box-sizing` `content-box`so that it is displayed correctly.
before:
after:
=> fix(Popover): fix display-issue-with-popover-arrow

packages/react/src/components/List/List.module.css, packages/react/src/components/List/List.stories.mdx, packages/react/src/components/List/List.test.tsx, packages/react/src/components/List/List.tsx, packages/react/src/components/List/ListItem.module.css, packages/react/src/components/List/ListItem.tsx, packages/react/src/components/List/index.ts, packages/react/src/components/index.ts
Copy of `List` component from Altinn's design system, with a couple of simplifications:
- Changed border style type to be a string literal instead of an enum
- Removed the context, it didn't seem to be necessary
- https://github.com/Altinn/altinn-design-system/issues/235
=> feat(List): Add list component

packages/react/src/components/HelpText/HelpText.tsx
Change the type of helptext children from string to ReactNode.
=> feat(HelpText): take reactnode instead of string

packages/react/src/components/CheckboxGroup/CheckboxGroup.test.tsx, packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx
Handling state externally and updating the list of CheckboxOptions given to the component potentially caused an infinite render loop. 
Changing the useEffect to the custom hook useUpdate and passing a stringified version of the items instead of the items themselves. 
The useUpdate will now only run if the content of the items have changed, and not if only the object reference has changed.
=> fix(CheckboxGroup): fix state handling problem

packages/react/src/components/HelpText/HelpText.tsx, packages/react/src/components/Popover/Popover.tsx
Changed role to tooltip for help-text in order to make its content accessible for NVDA screenreader when the content does not contain interactable elements.
=> fix(HelpText): helptext´s content not reachable with NVDA screenreader

.editorconfig, .vscode/extensions.json
We need an editorconfig so IDE behave the same across operating systems.
=> chore: :technologist: Added editorconfig

packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx
This suggests a fix for the Select component, enabling it to once again to accept changes to its option prop and updating the options displayed to the user as a result. This functionality was present before but was likely crippled at some point.
Tests for this dynamic change in options have been added.
[Related issue](https://github.com/Altinn/altinn-access-management-frontend/issues/217)
=> fix(Select): Support dynamically changing options

package.json, tsconfig.json, yarn.lock
Found this nifty plugin to typescript that gives us typing for `css` files: https://www.npmjs.com/package/typescript-plugin-css-modules
=> chore: :technologist: Added typesafety to css modules

packages/react/src/components/Button/Button.module.css
Adjusted padding to make quiet button with only icon completely round. Related to #187
=> fix(Button): adjust padding to make icon round

packages/react/src/components/RadioButton/RadioButton.module.css, packages/react/src/components/RadioButton/RadioButton.stories.mdx
The issue is caused by rounding errors for the inner checkmark when the outer box uses a border that gets scaled by small fractions of a px.
Fixed by using outline instead of border
Also changed the checkmark from background-collor to box-shaddow so that it is visible in print mode. It's also way less likely to get roundoff errors when drawing a shaddow than when
I also updated the storybook to show all the relevant variants in checked mode (missing ones was compact, error, and disabled)
From https://digdir.github.io/designsystem/?path=/docs/kjernekomponenter-radiobutton--normal
- Compact view without any zoom (added this to storybook default view so that it becomes more obvious in case of a regression)
- 90 % zoom in chrome
- 125% zoom in chrome
=> fix(RadioButton): RadioButton looks wrong when zoming in browser

packages/react/package.json, packages/react/src/components/TextField/TextField.test.tsx, packages/react/src/components/TextField/TextField.tsx, yarn.lock
=> fix(Textfield): upgrading `react-number-format`, removing workaround

package.json
I usually test the designsystem on app-frontend-react when making changes, and the only good way of doing that seems to be creating a local package and importing it into app-frontend-react (unless someone has found a way to link them without react self-destructing).
This is just a simple command to make it more convenient to package the react-package locally.
=> chore: Added yarn pack script

packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx
When setting an initial value to a select, it currently does not work if the options are loaded after the initial value is, since it will already have run the useEffect without finding the option and is not run again once the options are loaded. In app-fronten-react, this led to select-boxes always showing up empty on refresh even if they had been previously filled out, because option-loading happens later than formData-loading in app-frontend-react.
=> fix(Select): Update selected on option change

packages/react/src/components/Table/TableCell.tsx
In the frontendrepo the arrows colors don't work as they should. The arrows should be grey when not active and black when the sorting is Active. Fixed this in the old designsystem with a PR and got it to work, but I have not tested this but it is the same as I did in the old designsystem :)
=> fix(Table): Sort-arrows fix

packages/react/src/components/Checkbox/Checkbox.test.tsx, packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx, packages/react/src/components/FieldSet/FieldSet.tsx, packages/react/src/components/RadioButton/RadioButton.test.tsx, packages/react/src/components/RadioGroup/RadioGroup.tsx, packages/react/src/components/Table/TableCell.tsx, packages/react/src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.tsx
In relation to this task:
- https://github.com/Altinn/app-frontend-react/issues/583
We have the need to display some form components inside a table, for this to work nicely with screen readers we need to include `aria-label` to describe the inputs even when there is no description of them visible to normal users (where the visual position in the table is description enough).
Descriptions of what I did and why:
- Radio options had the option of hiding the label, but that prop was not accepted for checkbox options. I found that option useful, as it could render `aria-label` while not displaying the option label in the table.
- When the `hideLabel` option was used for radio/checkbox options, a `<label>` element still wrapped the element, but that label did not contain any text, which made …
=> fix(Table/RadioGroup/CheckboxGroup/FieldSet): Multiple minor accessibility improvements

packages/react/src/components/Table/TableCell.tsx
Our automated a11y tester found a problem with the `aria-sort` attribute, as it used an invalid value of `none` when the column was not sorted. Although [MDN says this value is valid](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort) (and the default), omitting it should have the same effect as using the default value, and the a11y stops complaining when this is not set.
=> fix(Table): Omitting `aria-sort` when no sort order is in effect

packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx, packages/react/src/hooks/useEventListener.test.ts, packages/react/src/hooks/useEventListener.ts, packages/react/src/hooks/useFocusWithin.test.tsx, packages/react/src/hooks/useFocusWithin.ts, packages/react/src/hooks/useKeyboardEventListener.test.ts, packages/react/src/hooks/useKeyboardEventListener.ts
- Added an element parameter to the event listener hooks, so that event listeners may be created locally, and applied this in the `Select` component.
- Moved the `hasFocus` functionality out to a separate hook to make the code a little bit cleaner. This will also be useful to the `InputWrapper` component as it may fix the last task of #129.
=> fix(Select): Make event listeners local

tsconfig.json
fixes: #138
Remove tsconfig linting rules as its causing unwanted consquences and we use eslint for linting.
=> chore: :wrench: Remove tsconfig linter rules

.gitignore, packages/tokens/build.ts
resolves #342 
Added support for `fontSize` transformation to css [clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp) functions
=> chore: :construction_worker: Support for fluid typography in tokens

design-tokens/$themes.json, design-tokens/Base/Semantic.json
- Changed focus-token from purple to yellow (outline)
- Added box-shadow-color 
- Deleted old tab-focus spacing token
- Changed name from "tab-focus" to "focus" since this will be visible as standard focus, not only when using a keyboard to navigate. 
Related to https://github.com/digdir/designsystem/issues/269
=> style: changed focus style tokens

packages/tokens/build.ts
Found a bug where the first "brand" that was processed didn't have the correct font scale available due to transformation and order of files being decided by style dictionary due to token references
=> chore: :bug: Fixed token transformation for global hack

packages/react/src/components/FieldSet/FieldSet.module.css
This mistakenly overwrote every usage of FieldSet that either set size to small or set not size at all
See quickfix in app-frontend-react:
- https://github.com/Altinn/app-frontend-react/pull/1145
=> fix(FieldSet): Fixing typo in font size

vercel.json
Added Vercel config that disable vercel auto-deployment for the `github-pages-deployment` branch used for storybook.
There is also an option to disable Vercel from commenting on PRs. Seems like the bot is also commenting on ignored deployments... I turned off Vercel bot comments by setting silent to true. Those comments might be nice if you are working on a repo that only contains a Next.js application. But for a monorepo this just becomes an annoyance (?).
Documentation: https://vercel.com/docs/concepts/projects/project-configuration/git-configuration
=> build: added vercel config for storybook branch

.storybook/preview.tsx
Added support for using the same viewports defined in Figma to be used in Storybook. This is done by reading the `$metadata.json` file from figma token studio and using sets containing "viewport" as width is defined in the name :)
=> chore: :lipstick: Synchronize viewports between Figma and Storybook

.storybook/preview-head.html, docs-components/BetaBlock/BetaBlock.module.css, docs-components/BetaBlock/BetaBlock.tsx, docs-components/TokenBlock/TokenBlock.module.css, docs-components/TokenBlock/TokenBlock.tsx, docs-components/index.ts, packages/react/src/components/Accordion/Accordion.mdx, packages/react/src/components/Accordion/Accordion.stories.tsx, packages/react/src/components/Accordion/Accordion.tsx, packages/react/src/components/Accordion/AccordionContent.tsx, packages/react/src/components/Accordion/AccordionHeader.tsx, packages/react/src/components/Accordion/AccordionItem.tsx, packages/react/src/components/Accordion/index.ts, packages/react/src/components/Typography/Typography.mdx
resolves #400 
- Some overrides for storybook styling to give more air in the bottom
- Added `TokenBlock` for reminder to use new token package
- Tweaked `BetaBlock` to match `TokenBlock` and be more in style with our upcoming alert
- Changed how compound props for `Accordion` as old way didn't work with props table and default values
- Cleaned up story and updated docs on all props
=> refactor: Improve Accordion component & stories

packages/react/src/components/Accordion/index.ts
This fix is so that the correct component name for sub-components are displayed when using react dev tools and "show code" in Storybook.
Normally `displayName` is derived from the const name of declared component, but since we are exposing them are sub-components (of compound component) we need to overwrite the `displayName` with the correct sub-component name.
=> fix(Accordion): :bug: Fix `displayName` for Accordion sub-components

packages/react/src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.module.css, packages/react/src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.tsx
Ensure to remove spacing/gap when the label is hidden on checkboxes and radio.
This PR resolved #384 :)
=> fix(CheckboxRadioTemplate): ensure to remove spacing/gap when label is hidden

packages/react/package.json, packages/react/src/components/Accordion/AccordionHeader.tsx, packages/react/src/components/Button/Button.test.tsx, packages/react/src/components/SvgIcon/SvgIcon.test.tsx, yarn.lock
The new aksel icon package was introduced in #393 so I updated our dependency in react package and changed usage from old to new package where they were used. 
Did not update icon for `HelpText` as there is a separate issue for that #444. Will not be able to remove the dependency for old package until this issue is resolved.
=> build: :heavy_plus_sign: Added `@navikt/aksel-icons` dependency to react package

packages/react/src/components/Typography/ErrorMessage/ErrorMessage.module.css, packages/react/src/components/Typography/Heading/Heading.module.css, packages/react/src/components/Typography/Ingress/Ingress.module.css, packages/react/src/components/Typography/Label/Label.module.css, packages/react/src/components/Typography/Paragraph/Paragraph.module.css
resolves #431
We decided to not force font-family to `Inter` for our users in #345
This is just a temporary solution to inherit font-family as `font` css shorthand needs to have a font-family defined (and not inherit). 
Will make a better solution for this in tokens transformer at a later point
=> fix(Typography): :bug: Fix Typography components to inherit font-family

packages/react/src/components/Table/TableCell.module.css, packages/react/src/components/Table/TableCell.tsx, packages/react/src/components/Table/TableHeader.module.css
Removed padding in header cells to make the content aligned with the content of normal cells. Fixes #388.
Did also remove a reference to an nonexistent CSS class.
=> fix(Table): Remove padding in header cells

packages/react/src/components/_InputWrapper/InputWrapper.module.css, packages/react/src/components/_InputWrapper/InputWrapper.tsx
Earlier we used the native `<span/>` element to render content about how many characters remain. This is now replaced with `ErrorMessage` and `Paragraph` to ensure the fonts to behaves according to other components within digdir-designsystem. Since we are using the `ErrorMessage` component, we do not need to set the error colour within the `InputWrapper.module.css.`.
=> refactor(InputWrapper): use the ErrorMessage and Paragraph

packages/react/src/components/Alert/Alert.module.css
resolves: #505 
Should use box-shadow as border-left instead of the border-left property. This is done to have the border on the inside of the box just like it is in Figma.
=> refactor(Alert): use box-shadow as border-left

design-tokens/Base/Core.json, yarn.lock
Removed border_radius properties from Core.json to avoid conflicts with Semantic.json.
=> style: remove border radius tokens from core

packages/react/src/components/Alert/Alert.module.css
Resolved: #549 
When elevated is set to true, the box-shadow property is used for the displayed shadow, hence we cannot use the same property to make the left border. Therefore I changed it to filter(drop-shadow). 
**Note**
We cannot use border-left because it conflicts with the Figma implementation. [More details can be found here.](https://github.com/digdir/designsystem/pull/532)
=> fix(Alert): avoid the border-left to disappear when elevated is true

design-tokens/Base/Semantic.json
Talked to @Febakke today about labels used next to radio and checkboxes. It looks a bit weird when they are the same weight and size as their legend. They should use medium weight while the rest of the labels and legends use font-weight semibold.
=> style: added label with correct weight for radio

design-tokens/$themes.json, design-tokens/Base/Component.json, design-tokens/Base/Semantic.json, design-tokens/Brand/Digdir.json, design-tokens/Brand/Tilsynet.json
BREAKING-CHANGE: The action-color for `surface`, `border` and `text` is diveded into primary and secondary action colors. 
Resolves #440 
The action-color for `surface`, `border` and `text` is diveded into primary and secondary action colors. 
Old structure was: 
```
surface {
neutral 
action
success
danger
}
```
New structure is: 
```
surface {
neutral 
action {
primary { }
secondary { }
success
danger
}
```
The brand-set can override primary and secondary action colors:
=> style(Tokens)!: added themeable action color tokens

packages/react/src/components/TextField/TextField.test.tsx, packages/react/src/components/TextField/TextField.tsx
As a step towards increasing the flexibility of the `TextField` component, I have added the `type` attribute and restricted its possible values to types that are appropriate with its styling. This makes it possible to use native features like date picker, integer selector etc.
Ideally, the component should extend `input` props, but this is not straightforward because of restrictions on the number format implementation. This should probably be extracted into a separate component in the future.
=> feat(TextField): Type attribute

design-tokens/Base/Semantic.json
Needed to change from dollar sign to curly brackets to ensure that style-dictionary successfully created RGBA tokens. With dollar signs, style-dictionary could not resolve the colour reference.
=> style: replaced dollar sign with curly brackets

README.md, storefront/components/MdxContent/MdxContent.module.css, storefront/components/Meta/Meta.tsx
Resolved #632 
* Changed font-size of numbered lists to 18px, which is the same as ul.
* Added a small space if a ul/ol is inside another ul/ol
* Changed line-height of items inside ul/ol from 1.7em to 1.9em.
Other fixes:
* Added favicon link to Head.
* Updated readme with storefront link.
* Added link styling to links inside ol.
=> chore: storefront ol styling

packages/tokens/README.md
Fixed spelling issue within Readme. 
This PR was created to pump token-package to a new version, since earlier commits did not follow correct commit-conventions.
=> fix(Readme): fixed spelling issue

packages/react/src/components/Tag/Tag.mdx, packages/react/src/components/Tag/Tag.stories.tsx
Cleaned up the code to use the existing `Stack` component and decorators for layout of code in stories. 
We use [decorators](https://storybook.js.org/docs/react/writing-stories/decorators/) for "wrapper code" that we don't want to be in the "show code" preview.
=> refactor(Tag): :recycle: Refactored `Tag` story to use existing `Stack` component for stories

packages/react/src/components/Chip/Chip.stories.tsx, packages/react/src/components/Chip/Group/Group.tsx, packages/react/src/components/Chip/Toggle/Toggle.tsx, packages/react/src/components/Chip/_ChipBase/ChipBase.tsx, packages/react/src/components/Chip/index.ts
Use context instead of clonelement for applying sizes to children
=> refactor(Chip): :recycle: Improve `Chip.Group` application of childrens sizes

packages/react/src/components/form/Radio/Group/Group.stories.tsx, packages/react/src/components/form/Radio/Group/Group.test.tsx, packages/react/src/components/form/Radio/Group/Group.tsx, packages/react/src/components/form/Radio/Radio.module.css, packages/react/src/components/form/Radio/Radio.tsx, packages/react/src/components/form/Radio/useRadio.ts
- Changed `onChange` in `Radio.Group` to return just value. Users can use `onChange` on `Radio` to get change event if needed
- Updated `label` to use regular font weight to Figma and have a distinction from `legend`
=> refactor(Radio): :recycle: Changes to `Radio` to conform with new `Checkbox`

packages/react/src/components/form/Checkbox/Checkbox.mdx, packages/react/src/components/form/Checkbox/Checkbox.module.css, packages/react/src/components/form/Checkbox/Checkbox.stories.tsx, packages/react/src/components/form/Checkbox/Checkbox.test.tsx, packages/react/src/components/form/Checkbox/Checkbox.tsx, packages/react/src/components/form/Checkbox/Group/Group.module.css, packages/react/src/components/form/Checkbox/Group/Group.stories.tsx, packages/react/src/components/form/Checkbox/Group/Group.test.tsx, packages/react/src/components/form/Checkbox/Group/Group.tsx, packages/react/src/components/form/Checkbox/Group/index.ts, packages/react/src/components/form/Checkbox/index.ts, packages/react/src/components/form/Checkbox/useCheckbox.ts, packages/react/src/components/form/Fieldset/Fieldset.tsx, packages/react/src/components/form/useFormField.test.tsx
resolves #630 
- New `Checkbox` component
- Added `hideLabel` to `Fieldset` which visually hides `legend` and `description`. This features is enabled for both `Checkbox.Group` and `Radio.Group`
- Did some changes to `Radio` to conform #691   
- Updated `label` to use regular font weight to Figma and have a distinction from `legend`
=> feat(Checkbox): ✨ New `Checkbox` component (unreleased)

packages/react/src/components/Pagination/Pagination.tsx
Fixes accessilbility checkers (siteimprove) complaining about missing `alt` text for img elements, since Aksel icons have role="img"
=> fix(Pagination): :wheelchair: Fix 'a11y' error for Pagination next/prev buttons

packages/react/src/components/Button/Button.module.css, packages/react/src/components/Button/Button.tsx
resolves: #684 
Avoid wrapping text content within <span> tags. This practice has led to problems when creating Cypress tests. The root cause is that Cypress identifies elements based on their text content, and encounters a non-clickable element such as a <span>. This led to the test breaking because Cypress does not click on non-clickable elements.
=> refactor(Button): render button text-content without wrapping in span

packages/react/src/components/_InputWrapper/InputWrapper.test.tsx, packages/react/src/components/_InputWrapper/InputWrapper.tsx
resolves: #719 
If characterLimit is invalid but the isValid has been set to true by the consumer, it should override the characterLimit validation
=> refactor(InputWrapper): isValid should override the characterLimit

packages/react/src/components/_InputWrapper/InputWrapper.test.tsx, packages/react/src/components/_InputWrapper/InputWrapper.tsx
resolves: #731 
Only isValid prop should decide the variant of the input field. (error or not)
=> fix(InputWrapper): isValid works now independent of charLimit validation

packages/react/src/components/Chip/Removable/Removable.module.css, packages/react/src/components/Chip/Removable/Removable.tsx, packages/react/src/components/Chip/_ChipBase/ChipBase.module.css
- Applied vertical padding to the `.label` class.
- Changed the hover/focus effect of removable chips so that the red background is applied to the root component with the help of `linear-gradient`. This way, there's no need to tweak the cross mark element with border-radius and box-shadow properties.
Fixes #747.
=> fix(Chip): Proper styling on tall chips

storefront/pages/grunnleggende/designelementer/design-tokens.mdx
The description for use of tokens for developers was wrong in the storefront. 
Changed it so that it links to the npm package. How to use tokens should follow the README on npm to avoid duplicate docs that will become out of sync
=> docs: :memo: Clarify use of tokens npms package in storefront

packages/react/src/components/form/Checkbox/Checkbox.module.css, packages/react/src/components/form/Radio/Radio.module.css, packages/react/src/components/form/Switch/Switch.module.css
fixes #789
Seems to me it still works as before, can't remember why that z-index was there to begin with, might be leftover code.
=> fix(Radio, Checkbox, Switch): :bug: Remove z-index on selection control icon

packages/react/src/utility-components/AnimateHeight/AnimateHeight.module.css
This PR adds the `aria-hidden` attribute to content in Accordions when they are closed.
- Closes #814
=> fix(Accordion): hide content in Accordions from screen readers when Accordion is closed

packages/react/src/components/Typography/ErrorMessage/ErrorMessage.module.css, packages/react/src/components/Typography/ErrorMessage/ErrorMessage.stories.tsx, packages/react/src/components/Typography/ErrorMessage/ErrorMessage.tsx
- Added option to toggle error color. 
- Needed for use-cases such as character count feedback that switches to error when limit is excedded. 
- Defaults to `true` so no breaking change
=> feat(ErrorMessage): :sparkles: Add new option to toggle error color

packages/react/src/components/Accordion/Accordion.module.css, packages/react/src/components/Accordion/AccordionHeader/AccordionHeader.tsx, packages/react/src/components/Button/Button.module.css, packages/react/src/components/Button/Button.tsx, packages/react/src/components/Chip/_ChipBase/ChipBase.module.css, packages/react/src/components/Chip/_ChipBase/ChipBase.tsx, packages/react/src/utils/utility.module.css
Made sure focus behaviour is consitent across current "felles" components by using the same focus class instead of individual implementations. This will make it easier to tune focus behaviour in future.
`Checkbox`, `Radio` & `Switch` still has indiviual implementation due to use of svgs.
Changes:
- Accordion, Button & Chip have now only focus on keyboard interaction.
- Accordion focus border is square as it had a visual bug being rounded since underlying shape is square
=> feat(Button, Chip, Accordion): :recycle: Change components to use the same class for focus behaviour

design-tokens/README.md
=> docs: :pencil2: Fixed typo for file path using tokens in Token studio

.github/workflows/storybook-deploy-vercel.yml
Add a github action for storybook vercel deployment so we can test it on storybook.designsystemet.no when DNS is ready.
Then we can replace `storybook-deploy.yml` with this when we are happy (remove action for gh-pages).
This action is identical to the storybook preview action except I:
*  Changed to trigger on main changes
*  Remove if checks
* Changed environment to production
*  Removed comment to PR feature
=> ci: add storybook vercel github action

packages/react/src/components/ToggleGroup/ToggleGroup.stories.tsx, packages/react/src/components/ToggleGroup/ToggleGroupItem/ToggleGroupItem.tsx
Adds accessible tilte for ToggleGroupItems to be used when only icons are displayed.
=> feat(ToggleGroup): Add accessible title for items with only icon

packages/react/src/components/Accordion/Accordion.module.css, packages/react/src/components/Accordion/AccordionContent/AccordionContent.tsx
This pull request solves two issues:
- It is not possible to override the bottom border styling of the accordion using a custom class name directly (it is necessary to either use complex selectors like `> div` or hard code the generated `contentWrapper` class name, which is not ideal).
- When using the bordered variant of the accordion, the bottom border is doubled.
=> fix(Accordion): Make border styling overridable

storefront/components/Meta/Meta.tsx
Resolves #874
An import to Inter was already in `globals.css`, so I just removed the link tag in head.
=> chore(storefront): remove link tag, Inter is already in globals.css

packages/react/src/components/Select/OptionList/OptionList.module.css, packages/react/src/components/Select/OptionList/OptionList.test.tsx, packages/react/src/components/Select/OptionList/OptionList.tsx, packages/react/src/components/Select/Select.tsx
The recent fix on hiding the option list did not not work in Altinn Studio, although I was able to reproduce the issue and fix it within Storybook. In Studio, it only made tests fail because React Testing Library interpreted the list as hidden by default. We need to dig deeper into this, but until we have a final fix, i think it is best to revert the current one, to avoid further troubles with automated testing.
=> Revert "fix(Select): Hide list when reference is hidden (#917)"

packages/react/src/components/Button/Button.module.css, packages/react/src/components/Button/Button.tsx
BREAKING CHANGE: Removed `dashedBorder` prop
resolves #942
=> feat(Button): :boom: Removed `dashedBorder`

.eslintignore, .eslintrc.js, package.json, packages/react/src/components/Button/Button.mdx, packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/form/Switch/Switch.mdx, packages/react/src/components/form/Switch/Switch.stories.tsx, yarn.lock
When upgrading to latest Storybook a recommendation for installing their eslint plugin popped up. 
Suggest using this to keep things consistens in accordance with Storybook guidelines.
=> chore: ➕ Add `eslint-plugin-storybook`

.eslintrc.js, apps/storefront/pages/god-praksis/index.mdx, apps/storefront/pages/grunnleggende/introduksjon/designprinsipper.mdx, packages/tokens/scripts/build.ts
- Fixed save path for token storefront build
- Simplified brand type used in tokens build so its easier to overwrite in fork
- Fixed eslint and prettier not cooperating when using format on save
- Fixed some typos in links to github storefront folder
=> chore: :building_construction: Fix IDE formatting and bugs after `apps/storefront` move

packages/react/src/utils/utility.module.css
=> style(focus): Use correct color tokens for `.focusable`

.github/workflows/storefront-preview.yml, .github/workflows/storybook-preview.yml, apps/storefront/pages/index.mdx
I used UTC offset initially to set the timezone but that will not work throughout the year.
Changed to using the `timezone` config: https://github.com/josStorer/get-current-time#timezone
Tested that it works in this PR.
=> chore: fix timezone in github action preview comments

packages/react/src/components/List/List.stories.tsx, packages/react/src/components/List/List.tsx
Suggest keeping it simple and just use the default type for `children`
=> fix(List): :label: Default type for `children`

packages/react/src/components/Divider/Divider.tsx
We were not able to send `HTMLHRElement` props to the `Divider` element.
=> fix(Divider): Add so it can recieve `HTMLHRElement` props

packages/react/src/components/Box/Box.test.tsx, packages/react/src/types/OverridableComponent.ts
Adds `displayName` to the `OverridableComponent` type
=> fix(OverridableComponent): Add `displayName` to type

apps/storefront/components/Image/Image.module.css, apps/storefront/components/Image/Image.tsx, apps/storefront/components/Image/index.ts, apps/storefront/components/index.ts, apps/storefront/pages/grunnleggende/for-designere/kom-i-gang.mdx
Feature request from @mrosvik:
Added an `Image` component so that editors can toggle boxShadow and maybe other preperties in the future in MDX.
Styling:
* Images have a boxShadow by default in MDX, so I reset it in the `.container .img` selector and also moved the margin to the `.container` class.
=> chore(storefront): Added Image component to be able to toggle boxShadow

packages/react/rollup.config.js
fixes #1110
Tested using `Search` and `Checkbox` codesandbox example @Magnusrm. Seems to fix the problem for now
This is a temporary fix for when components are tree-shaked and dependant components imported. This will reverse the order of when they are injected into `<head>` making so that we get the correct order for defining css classes.
Downside with this approach is that it puts our css at the very top in our users `<head>`. Hopefully this wont cause problems for their CSS as we dont have any "global" css, only our own classes. Note that the injection to top of `head` happens once the script tag in `<head>` with the component code is resolved by the browser. 
When we get our css package in order and remove reliance on CSS-in-JS we can remove this entirely.
After:
=> fix: :bug: Temporary change order for injected CSS

packages/react/rollup.config.js, packages/react/scripts/name.js
Trying to fix #1110 again
- Disabling tree-shaking until we get our css-package published to reduce (hopefully negate) css-in-jss being injected in the wrong order when components are internally dependant on each other. 
- One drawback is that this will result in potential bigger bundles for our end users for the time being. 
- Added hash for our generated css classnames as we were getting duplicates, exampled being `LegacyPopover` vs `Popover`
=> fix(Checkbox, Radio, Search): 🐛 Styling interferences 

packages/react/src/components/form/Textarea/Textarea.module.css, packages/react/src/components/form/Textfield/Textfield.module.css
Revert changes that had unintended consequences, preventing `size="small"` `input` from being "small" (36px).
=> refactor(Textarea, Textfield): :rewind: Revert absolute `min-height` value

packages/react/src/components/form/NativeSelect/NativeSelect.module.css
Fixes the `background-color` in Firefox being the wrong color:
=> fix(NativeSelect): Fix firefox background color

packages/react/src/components/ToggleGroup/ToggleGroup.test.tsx, packages/react/src/components/ToggleGroup/ToggleGroup.tsx
=> feat(ToggleGroup): Support `form` when `name` is provided

packages/react/src/components/Chip/Chip.module.css, packages/react/src/components/Chip/Chip.stories.tsx, packages/react/src/components/Chip/Removable/Removable.stories.tsx, packages/react/src/components/Chip/Removable/Removable.tsx, packages/react/src/components/Chip/Toggle/Toggle.stories.tsx
fixes #1291
- Added correct heights on x-mark icon
- Updated to use correct `size` in stories
- Conformed markup
=> fix(Chips): :bug: Correct sizings

packages/react/src/components/Tag/Tag.mdx, packages/react/src/components/Tag/Tag.module.css, packages/react/src/components/Tag/Tag.stories.tsx, packages/react/src/components/Tag/Tag.test.tsx, packages/react/src/components/Tag/Tag.tsx
**This is a breaking change**
To differentiate `Tag` from `Button`, three things have been changed:
-  Primary (dark) version has been removed, thus removing the variant prop
-  Border on light version has been removed
-  Warning tag now uses token: `surface-warning-default` instead of `surface-warning-subtle`
Resolves #1261
=> feat(Tag): New Tag design

design-tokens/$themes.json
Resolves [#1349](https://github.com/digdir/designsystemet/issues/1349)
=> chore(tokens): Remove old density set

packages/react/src/components/form/Radio/Group/Group.module.css, packages/react/src/components/form/Radio/Group/Group.tsx, packages/react/src/components/form/Radio/Radio.module.css, packages/react/src/components/form/Radio/Radio.tsx
resolves #1222
- Much simpler html and css than previous
- Still some trickery with box-shadows used for hover, border and background when checked.
- Some updates to match Figma design better
- Using `rem` instead of our fluid sizing tokens as browsers handle rounding half pixels different making skewed circles.
- Its still possible to get skewed circles if user has changed root font-size but we hope it happens less this way.
=> refactor(Radio): :recycle: Replace radio SVG icon with CSS

packages/react/src/components/form/Checkbox/Checkbox.module.css, packages/react/src/components/form/Checkbox/Checkbox.tsx, packages/react/src/components/form/Checkbox/Group/Group.module.css, packages/react/src/components/form/Checkbox/Group/Group.tsx
resolves #1223
- Mostly just copied css from `Radio`. 
- Changed border-radius and added background-image with encoded svg for "checked" mark.
- Updated with thicker checkmark icon after discussions on slack: https://designsystemet.slack.com/archives/C05U1MNKYCX/p1704983538260269
Did not base64 encode the svg due to: https://css-tricks.com/probably-dont-base64-svg/ and testing locally, the url encoded svg was about smaller. This will also make it easier to adjust in the future.
=> refactor(Checkbox): ♻️ Replace checkbox SVG icon with CSS

packages/react/src/components/form/Checkbox/Checkbox.tsx
Removed old code I forgot when refactoring checkbox to CSS in #1373
=> refactor(Checkbox): :recycle: Remove deprecated children check

packages/react/src/components/Button/Button.module.css, packages/react/src/components/Button/Button.stories.tsx
fixes #1448
was not able to get to work in Storybook, probably due to it having its own postcss transpiler config.
=> fix(Button): :bug:  Passed `className` should now override correctly

packages/react/src/components/Link/Link.tsx
=> feat(Link): Add `asChild` support to `Link`

packages/react/src/utilities/RovingTabIndex/RovingTabindexRoot.tsx
=> feat(RovingTabindexRoot): Add `asChild` support to `RovingTabindexRoot`

packages/react/src/utilities/RovingTabIndex/RovingTabindexItem.tsx
=> feat(RovingTabindexItem): Add `asChild` support to `RovingTabindexItem`

packages/react/src/components/Typography/ErrorMessage/ErrorMessage.tsx
=> feat(ErrorMessage): Add `asChild` support to `ErrorMessage`

packages/react/src/components/Button/Button.tsx
=> feat(Button): Add `asChild` support to `Button`

packages/react/src/components/Typography/Paragraph/Paragraph.tsx
=> feat(Paragraph): Add `asChild` support to `Paragraph`

packages/react/src/components/Typography/Label/Label.tsx
=> feat(Label): Add `asChild` support to `Label`

apps/storefront/layouts/NotFoundLayout/NotFoundLayout.tsx, apps/storefront/layouts/PageLayout/PageLayout.tsx
Next was complaining about using `as`, changed these to use `asChild`
=> chore(storefront): Fix build errors with using `as`

packages/react/src/components/Table/Table.test.tsx, packages/react/src/components/Table/Table.tsx, packages/react/src/components/Table/TableCell.tsx, packages/react/src/components/Table/TableHeaderCell.tsx
Fixes #1499 
Update types to correctly include native attributes.
Checked against [IntrinsicElements](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8b8da1a8fb5d33e7bee46d971cbf8aea10aeacb8/types/react/ts5.0/index.d.ts#L3980) to use same types as React does internally.
Omitted [border](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement/border) from native `<table>` props as it interfered with ours. The native one is marked as obsolete/deprecated so I think its safe to use as our own.
=> fix(Table): :label: Fix types

package.json
Running Storybook from a fresh git clone failed as packages were not found due to missing npm link.
=> build: :building_construction: Add missing folders to workspaces

packages/react/src/components/DropdownMenu/DropdownMenuTrigger.tsx, packages/react/src/components/ErrorSummary/ErrorSummaryHeading.tsx, packages/react/src/components/ErrorSummary/ErrorSummaryItem.tsx, packages/react/src/components/Modal/ModalTrigger/ModalTrigger.tsx, packages/react/src/components/Popover/PopoverTrigger.tsx
Some components did not need their own `asChild` props.
Also fixed an instance where `asChild` was wrong, and not using `Slot`
=> chore: Fix use of `asChild` in some components

packages/react/src/components/Button/Button.module.css
Removed due to interfering with using `display` to toggle different icons.
=> fix(Button): Remove `display: inline-block` for icons

packages/react/src/components/ErrorSummary/ErrorSummaryItem.tsx
resolves #1560
Also fixes lost styling from `Link` when using `asChild`
=> fix(ErrorSummaryItem): `href` is optional when `asChild` is `true`

packages/react/src/components/form/Fieldset/Fieldset.module.css, packages/react/src/components/form/Fieldset/Fieldset.tsx
Here is another suggestion for making it easier to override the styling of `Fieldset`:
- Set `flex` properties directly on the `fieldset` element instead of using `margin-top` on `> :not(:first-child, :empty)`. This both simplifies the code and makes it easier to override it from the outside.
- Set `display: contents` on the legend and the error wrapper. This styles the elements like their contents, so there will be no unexpected gaps if they are empty. Also, the legend will behave like a normal element, placing itself inside the box and not on the border.
=> fix(Fieldset): Simplify CSS

packages/react/src/components/form/Combobox/Combobox.module.css
Resolves #1630
We might not need to use the `Box` component here, but this PR only changes the css to be transparent
=> style(Combobox): Add transparent background to wrapper

packages/react/src/components/Card/Card.module.css, packages/react/src/components/HelpText/HelpText.module.css, packages/react/src/components/Table/Table.module.css, packages/react/src/components/Tabs/Tab/Tab.module.css, packages/react/src/components/Tabs/TabContent/TabContent.module.css, packages/react/src/components/Tooltip/Tooltip.module.css, packages/react/src/components/Typography/ErrorMessage/ErrorMessage.module.css, packages/react/src/components/Typography/Heading/Heading.module.css, packages/react/src/components/Typography/Ingress/Ingress.module.css, packages/react/src/components/Typography/Label/Label.module.css, packages/react/src/components/Typography/Paragraph/Paragraph.module.css, packages/react/src/components/form/Combobox/Combobox.module.css, packages/react/src/components/form/Combobox/Custom/Custom.module.css, packages/react/src/components/form/Combobox/Empty/Empty.module.css, packages/react/src/components/form/Combobox/Option/Description/Description.module.css, packages/react/src/components/form/Combobox/Option/Option.module.css, packages/react/src/components/form/NativeSelect/NativeSelect.module.css, packages/react/src/components/form/Search/Search.module.css, packages/react/src/components/form/Textarea/Textarea.module.css, packages/react/src/components/form/Textfield/Textfield.module.css
Add `font-family: inherit;` after `font:`
potential fix for #1632
=> fix: Components should now inherit font-family correctly

packages/react/src/components/form/Fieldset/Fieldset.tsx
My recent change broke the `hideLegend` functionality since `display: contents` basically makes the legend ignore most of the styling applied to it. Fixed it by moving the `visuallyHidden` class to the child component.
=> fix(Fieldset): Make hideLegend work again

packages/react/src/components/form/Switch/Switch.module.css
Removed unused css, on had css syntax error and the stroke does nothing as `.track` is no longer an svg.
=> style(Switch): :fire: Remove dead css

apps/storefront/components/NavigationCard/NavigationCard.module.css, apps/storefront/pages/grunnleggende/index.mdx
* Fixed a broken link on the "Avstander" Card under "Grunnleggende".
* Changed icon to Ruler
* Added more spacing under title.
=> fix(storefront): Fixed broken link and NavCard styling

.gitattributes, packages/css/react-css-modules.css, packages/react/scripts/name.js
Now that we have checked in css thats generated from css-modules we need to change the hash for css-module classNames to be relative. 
It was using the absolute path for files before, which resulted in new classNames being generated for every unique location and build of source code.
=> build: Relative hash for css-modules

packages/react/src/components/form/Combobox/Combobox.stories.tsx, packages/react/src/components/form/Combobox/Combobox.tsx, packages/react/src/components/form/Combobox/internal/ComboboxClearButton.tsx, packages/react/src/components/form/Combobox/internal/ComboboxInput.tsx
Resolves #1701
This also deprecates `cleanButtonLabel`, as this should be `clearButtonLabel`
=> feat(Combobox): Add `hideClearButton` prop

apps/storefront/layouts/BlogArticleLayout/BlogArticleLayout.tsx, apps/storefront/pages/bloggen/2023/derfor-trenger-vi-et-felles-designsystem.mdx
Resolves #1656
Meta tags still work: https://metatags.io/?url=https%3A%2F%2Fstorefront-pr-1729.dev.designsystemet.no%2Fbloggen%2F2023%2Fderfor-trenger-vi-et-felles-designsystem
=> feat(storefront): Make image required in blog template

packages/react/src/components/form/Radio/Radio.tsx
When using `style`, it was being applied to the `input` element. We have decided to do it on the outermost element
=> fix(Radio): `style` applied to wrong element

packages/react/src/components/form/Checkbox/Checkbox.tsx
When using `style`, it was being applied to the `input` element. We have decided to do it on the outermost element
=> fix(Checkbox): `style` applied to wrong element

packages/react/package.json, packages/react/src/components/form/Combobox/Combobox.tsx, yarn.lock
Resolves #1730
Updates `@tanstack/react-virtual`
After some experimenting, it seems like this bug comes from the [library](https://tanstack.com/virtual/latest/docs/api/virtualizer) we are using.
It only happens when you scroll in the list container, close and open again.
If you scroll back to the top before closing, the error does not happen.
The only fix I found is to scroll back to the top before closing.
=> fix(Combobox): Fix `flushSync` being called inside a lifecycle method

.storybook/preview.tsx, packages/get-started.mdx, packages/react-old/src/components/legacy/LegacyTable/Table.stories.mdx, packages/react/src/components/Accordion/Accordion.mdx, packages/react/src/components/Alert/Alert.mdx, packages/react/src/components/Button/Button.mdx, packages/react/src/components/Card/Card.mdx, packages/react/src/components/Chip/Chip.mdx, packages/react/src/components/DropdownMenu/DropdownMenu.mdx, packages/react/src/components/ErrorSummary/ErrorSummary.mdx, packages/react/src/components/Link/Link.mdx, packages/react/src/components/List/List.mdx, packages/react/src/components/Pagination/Pagination.mdx, packages/react/src/components/Popover/Popover.mdx, packages/react/src/components/SkipLink/SkipLink.mdx, packages/react/src/components/Tabs/Tabs.mdx, packages/react/src/components/Tag/Tag.mdx, packages/react/src/components/ToggleGroup/ToggleGroup.mdx, packages/react/src/components/Typography/Typography.mdx, packages/react/src/components/form/Checkbox/Checkbox.mdx, packages/react/src/components/form/NativeSelect/NativeSelect.mdx, packages/react/src/components/form/Radio/Radio.mdx, packages/react/src/components/form/Switch/Switch.mdx
Resolves #1699
Get started page has the same text as our root readme, but in norwegian.
Removed all `<Information />`, except the ones telling the user about deprecation.
=> feat(storybook): Add getting started page

docs-components/DoAndDont/DoAndDont.tsx
We were not waiting for the image to load, so the first call was always `NaN` - when you had the image in cache, it would then update on later page loads in production. This gave us differing css on second page view.
Removed aspect ratio for now, we can adjust images to fit instead
=> fix(DoAndDont): Remove aspect ratio

docs-components/DoAndDont/DoAndDont.module.css, docs-components/DoAndDont/DoAndDont.tsx
Adds color back to do and dont. Also adds `sb-unstyled` class to text, so we use our own styling.
=> style(DoAndDont): CSS Updates

.storybook/main.ts, apps/dev/package.json, apps/storefront/package.json, package.json, yarn.lock
Fix as many as possible warnings when running `yarn`
Before:
After:
Removed also `@storybook/addon-mdx-gfm`
=> build: :green_heart: Fix yarn warnings about dependencies

packages/css/react-css-modules.css, packages/react/src/components/form/Radio/Radio.module.css
Fix copy-pasta 🍝 bug which causes missaligned radio and label.
=> fix(Radio): :bug: Correct orientation of radio and label

packages/css/package.json, packages/css/postcss.config.js, yarn.lock
Autoprefixer with browserslist config
Fixes #1669 
Fixes #1773
The suggested browserslist config was: 
`[">0.2%", "not dead", "not ie <= 11", "not op_mini all"]`
Using ">0.2%" is not recommended by browserslist: 
"[...] only using a percentage of usage numbers above 0.2% will in the long run make popular browsers even more popular. We might run into a monopoly and stagnation situation, as we had with Internet Explorer 6. Please use this setting with caution."
The default browserslist configuration is: "the [defaults](https://browsersl.ist/#q=defaults&region=NO) query which is a shortcut for > 0.5%, last 2 versions, Firefox ESR, not dead." 
Configuration can be targeted into country specific stats. I think the projects target audience is the Norwegian population. 
Taken all the above into …
=> feat(css): Add autoprefixer with configuration (#1669 #1773)

packages/react/src/components/Box/Box.stories.tsx, packages/react/src/components/DropdownMenu/DropdownMenu.stories.tsx, packages/react/src/components/DropdownMenu/DropdownMenu.test.tsx, packages/react/src/components/DropdownMenu/DropdownMenuTrigger.tsx, packages/react/src/components/Modal/ModalTrigger/ModalTrigger.tsx, packages/react/src/components/Popover/PopoverTrigger.tsx
resolves #1794 
BREAKING CHANGE: `DropdownMenu.Trigger`, `Modal.Trigger` & `Popover.Trigger` no longer clone style to child on `asChild`
- Reverted changes on hos Slot vs default component is used in `Trigger` components
- Updated `DropdownMenu` stories to use `asChild`
- Updated `Box` stories to use `asChild`
=> feat(DropdownMenu, Popover, Modal): Using `asChild` on `Trigger` components no longer clones style to child

packages/css/react-css-modules.css, packages/react/src/components/Accordion/Accordion.module.css
resolves #1827
Would need to rewrite css to target children since color is passed on top level. Saving this for later when we clean up css.
=> refactor(Accordion): :recycle: Change "gap" color token

.storybook/manager-head.html, .storybook/preview-head.html, README.md, apps/storefront/globals.css, apps/storefront/pages/grunnleggende/designelementer/typografi.mdx, packages/get-started.mdx
After we implemented cascade layers, we don't need to have `!important` on `font-feature-settings: 'cv05' 1;` anymore.
This removes this in our code, and our documentation
=> chore: Remove text about `!important`

packages/css/index.css, packages/css/react-css-modules.css, packages/react/src/components/Modal/ModalHeader/ModalHeader.module.css, packages/react/src/components/Modal/ModalHeader/ModalHeader.tsx
Sorts `fds.utils` and `fds.btn` first, since we use these components in other components - and want them to have lower priority.
Should probably do this to our typography components as well, but leaving that for another PR.
=> fix(Modal): fix close button position

packages/react/src/components/Chip/Removable/Removable.tsx, packages/react/src/components/Chip/Toggle/Toggle.tsx, packages/react/src/components/Typography/Paragraph/Paragraph.stories.tsx, packages/react/src/components/Typography/Paragraph/Paragraph.tsx, packages/react/src/components/Typography/Typography.stories.tsx, packages/react/src/components/form/Fieldset/Fieldset.tsx, packages/react/src/components/form/Textfield/Textfield.tsx
Seems like the typechecking did not catch a few things when we removed `short`, so I fixed this as well.
=> feat(Paragraph): Remove deprecated `as` prop

apps/storefront/components/Image/Image.module.css, apps/storefront/components/MdxContent/MdxContent.module.css, apps/storefront/components/ResponsiveIframe/ResponsiveIframe.module.css, apps/storefront/globals.css, apps/storefront/pages/grunnleggende/for-designere/kom-i-gang.mdx
resolves #1912 
resolves #1911 
resolves #1921
**Width of videos:** Added a CSS variable to set max-width on media elements. Added this to the `ResponsiveIframe` component that is used to show videos. /grunnleggende/for-designere/kom-i-gang has a video
**Lists wider than paragraph:** Added `ul` and `ol` tags to the same width as paragraphs.
**Code inside lists:** Added styling of the `code` tag to `ul` and `ol` lists.
=> chore(storefront): Fix smaller MDX styling issues

.storybook/preview.tsx
Removed reliance on viewports design tokens as these are planned to be removed in #1849
=> refactor: :building_construction: Use defined viewports in Storybook

packages/css/radio.css, packages/css/togglegroup.css, packages/react/src/components/ToggleGroup/ToggleGroupItem/ToggleGroupItem.module.css, packages/react/src/components/ToggleGroup/ToggleGroupItem/ToggleGroupItem.tsx, packages/react/src/components/form/Radio/Group/Group.module.css, packages/react/src/components/form/Radio/Group/Group.tsx
=> chore(Radio, ToggleGroup): ♻️ Move missed css to correct place

packages/css/button.css, packages/react/src/components/Button/Button.mdx, packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Button/Button.tsx, packages/react/src/utilities/getSize.ts, packages/react/stories/testing.stories.tsx
#1981
Added an internal utility function to give us the new size names, if a user passes an old one.
Had to change the type for the testing page.
=> feat(Button): add shorthand sizes

packages/css/box.css, packages/react/src/components/Box/Box.test.tsx, packages/react/src/components/Box/Box.tsx
=> feat(Box): add shorthand sizes

packages/css/tabs.css, packages/react/src/components/Tabs/Tab/Tab.tsx, packages/react/src/components/Tabs/Tab/useTab.ts
resolves #2054
I removed the class `fds-tabs__tab--active`, since we can make sure our users make use of correct aria attributes by selecting on `[aria-selected="true"]`
=> fix(Tabs): active tab has wrong hover style

packages/react/src/components/form/Fieldset/Fieldset.mdx, packages/react/src/components/form/Fieldset/Fieldset.stories.tsx
Was working on the fieldset and saw there was no preview in storybook.
=> chore(storybook): 🪧 Add fieldset preview

packages/css/heading.css, packages/react/src/components/Typography/Heading/Heading.tsx, packages/react/src/utilities/getSize.ts
Remove non working size `3xl` (previously `xxxlarge`). This was removed when we converted to static font scales so its not working today at all since token does not exits anymore
=> fix(Heading): :coffin: Remove non-working `3xlarge`/`3xl` size

packages/css/checkbox.css, packages/css/fieldset.css, packages/css/native-select.css, packages/css/radio.css, packages/css/search.css, packages/css/switch.css, packages/css/textarea.css, packages/css/textfield.css, packages/react/src/components/form/Checkbox/Checkbox.tsx, packages/react/src/components/form/Fieldset/Fieldset.tsx, packages/react/src/components/form/NativeSelect/NativeSelect.tsx, packages/react/src/components/form/Radio/Radio.tsx, packages/react/src/components/form/Switch/Switch.tsx, packages/react/src/components/form/Textarea/Textarea.tsx, packages/react/src/components/form/Textfield/Textfield.tsx
Part of #1952 
Removing classes where native selectors can be used.
=> feat(css): use native selectors

packages/react-old/package.json, packages/react-old/src/index.ts, yarn.lock
BREAKING CHANGE: Removes re-export of components from `@digdir/designsystemet-react`
=> feat: :heavy_minus_sign: Remove re-export of `@digdir/designsystemet-react` components

packages/css/textfield.css
We encountered an [issue](https://github.com/Altinn/altinn-studio/issues/13167) in Altinn Studio when we added prefix and suffix to the Textfield component. When a text inside a prefix/suffix contains a hyphen, a line break is created and the container overflows vertically.
The issue can be solved by adding `white-space: nowrap` to the prefix and suffix classes.
This is from testing in local Storybook.
**Before**:
**After**:
=> fix(Textfield): Disable word-wrapping inside prefix and suffix

.changeset/config.json, .changeset/friendly-islands-punch.md, .github/workflows/release-snapshot.yml, packages/react/src/components/form/Combobox/Combobox.test.tsx, packages/react/src/components/form/Combobox/internal/ComboboxClearButton.tsx, packages/react/src/components/form/Combobox/internal/ComboboxInput.tsx
=> fix(Combobox): :bug: Click to open/close should now close when open

.changeset/short-walls-judge.md, packages/react/src/components/form/Combobox/Combobox.test.tsx, packages/react/src/components/form/Combobox/Combobox.tsx
resolves #2179 
`label` type changed to `ReactNode`
=> feat(Combobox): :sparkles: Label now supports other elements

.changeset/hip-masks-greet.md, packages/css/button.css
After discussion in daily we will make button have `text-align: inherit` when not in full width.
This is to make line breaks within the button look nicer for the user
=> chore(Button): text-align: inherit when not in full width

.changeset/chilled-icons-chew.md, packages/react/src/components/Accordion/Accordion.stories.tsx, packages/react/src/utilities/AnimateHeight/AnimateHeight.test.tsx, packages/react/src/utilities/AnimateHeight/AnimateHeight.tsx
=> chore(Accordion): fix defaultOpen flicker on first render

.changeset/wise-countries-double.md, packages/react/src/components/form/NativeSelect/NativeSelect.test.tsx, packages/react/src/components/form/NativeSelect/NativeSelect.tsx, packages/react/src/components/form/NativeSelect/useNativeSelect.ts
=> feat(NativeSelect): add focus in `readOnly` state

.changeset/shaggy-bears-tan.md, packages/react/src/components/Modal/ModalDialog.tsx
=> chore(Modal): remove `FloatingFocusManager`

.changeset/eighty-cougars-think.md, packages/react/src/components/Tabs/TabList.tsx
makes arrow keys work in any direction, always.
=> chore(Tabs): set ambiguous orientation

biome.jsonc, packages/cli/bin/designsystemet.ts, packages/cli/src/migrations/codemods/css/plugins.ts, packages/cli/src/migrations/codemods/jsx/classname-prefix.ts, packages/cli/src/tokens/utils/permutateThemes.ts, packages/react/src/components/form/Combobox/Combobox.tsx, packages/react/src/components/form/Combobox/internal/ComboboxInput.tsx, packages/react/src/components/form/NativeSelect/NativeSelect.test.tsx
=> chore: replace `forEach` with `for..of`

.changeset/thin-icons-pay.md, apps/theme/app/testside/FullBaseTest/FullBaseTest.tsx, apps/theme/components/ColorPicker/ColorPicker.tsx, biome.jsonc, packages/cli/src/colors/colorUtils.ts, packages/react/src/components/Tabs/TabContent.tsx, packages/react/src/components/Tabs/useTab.ts, packages/react/src/components/ToggleGroup/ToggleGroupItem/useToggleGroupitem.ts, packages/react/src/utilities/RovingFocus/RovingFocusItem.tsx
=> chore: remove all double equals

.changeset/plenty-vans-sneeze.md, packages/css/accordion.css, packages/react/src/components/Accordion/AccordionHeading.tsx, packages/react/src/components/Accordion/AccordionItem.tsx, packages/react/src/components/Accordion/index.ts, packages/react/stories/bruk.mdx
streamlines AccordionHeading, which had wrong names in props, logs and documentation.
=> fix(AccordionHeading): correct exports and docs

apps/storefront/app/monstre/feilmeldinger/page.mdx, apps/storefront/app/monstre/obligatoriske-og-valgfrie-felt/page.mdx, apps/storefront/app/monstre/systemvarsler/page.mdx, apps/storefront/components/MdxContent/MdxContent.module.css, apps/storefront/siteConfig.tsx
fixes cards using wrong `color`.
fixes margin and padding in cards after we started using our own components.
fixes siteconfig having double of one page.
=> chore(storefront): fix cards in mdx content

packages/css/table.css
table with zebra enabled made zebra colored rows white on hover. Removed this.
This does not need a changeset, since the changes to table has not been pushed to next yet
=> style(Table): remove hover on zebra colored row

packages/cli/src/colors/theme.ts
Adding new base colors for orange and green so the contrast color becomes white.
=> chore: add new orange and green base colors

packages/cli/src/colors/theme.ts
we were displaying the wrong css variable in our color modals on storefront and theme.
First reported in Slack
=> fix: correct css var in color modal

.github/workflows/test-coverage.yml, package.json, vitest.config.mjs, yarn.lock
- Add support for test coverage so we easily can detect code that never have run during our rests
- Using vitest with v8
- Open the generated file `coverage/index.html` in a browser to explore
=> chore: add test coverage

.changeset/rich-carrots-deny.md, packages/react/src/components/Typography/Heading/Heading.tsx
=> feat(Heading): default level is now 2

.changeset/small-queens-breathe.md, packages/css/spinner.css, packages/react/src/components/Spinner/Spinner.test.tsx, packages/react/src/components/Spinner/Spinner.tsx
part of #2295
Though I'd like to use 
```html
<svg data-size="*" />
```
```css
width: attr(data-size px, '40px');
height: attr(data-size px, '40px');
```
this is not currently supported.
https://caniuse.com/?search=attr
=> feat(spinner): css changes and data attrs

packages/react/src/utilities/hooks/useSynchronizedAnimation/useSynchronizedAnimation.ts
Fixes issue when multiple skeletons or spinners are removed at different times, causing crash
The issue is because `firstOfType` might exist, but it might not have a `currentTime` and setting `myAnimation.currentTime = null` is not allowed.
Reported by Team Export Mattilsynet
=> fix: syncronized animation bug

.github/workflows/test-reports.yml
This is just a placeholder workflow, the actual contents of the workflow will be populated in #2400. But [the workflow dispatch GUI](https://github.com/digdir/designsystemet/actions/workflows/test-reports.yml) (and `gh workflow run` CLI) only works if the workflow file is already present on the default branch.
=> ci: add a "Test reports" workflow

.changeset/purple-berries-repeat.md, packages/css/tabs.css, packages/react/src/components/Tabs/Tab.tsx, packages/react/src/components/Tabs/TabsRoot.tsx
=> feat(tabs): css changes

apps/storefront/app/layout.tsx
Add the Siteimprove script tag and remove Vercel analytics. The Siteimprove tag should only be loaded when the Storefront is deployed from the main branch (production).
=> chore: add siteimprove to storefront

packages/css/link.css
- Issue caught by @Barsnes 🙌 
- Tiny adjustment to also align child images of link, preventing issues like:
=> fix(Link): align img icon

packages/css/baseline/typography.css, packages/react/src/components/Typography/Heading/Heading.tsx, packages/react/src/components/Typography/Label/Label.tsx, packages/react/src/components/Typography/Paragraph/Paragraph.tsx, packages/react/src/components/Typography/ValidationMessage/ValidationMessage.tsx
related to #2503
Doing everything in typography except ingress, since this will be removed.
Spacing now has to be on every class, but we have an issue about removing this.
We could also let it be outside the classes, since `data-spacing` is only used for typography components, and it needs the css var to do anything.
=> feat(typography): use classes for typography styles

apps/storybook/.storybook/main.ts, apps/storybook/.storybook/preview.tsx, apps/storybook/.storybook/style.css
Fixes white text and other color errors when changing to dark theme.
Updated to target only stories
Old:
=> fix(storybook): only theme on stories

packages/css/button.css, packages/css/chip.css, packages/css/postcss.config.js, packages/css/utilities.css
comment about why has been added in code.
We should also consider moving the focus style outside of its layer, to make sure it is less likely to be overridden
=> feat: `ds-focus` use both `outline` and `box-shadow`

packages/css/utilities.css
Sicne we don't set the focus vars on `data-ds-color-mode`, the color of the focus border is never changed since it is only calculated on `:root`
=> fix: focus changing color when changing mode

packages/css/card.css
=> fix(card): add `display: block`

.changeset/twelve-onions-laugh.md, apps/storybook/chromatic.config.json, package.json, packages/css/modal.css
See https://caniuse.com/mdn-css_selectors_backdrop_inherit_from_originating_element for affected versions.
=> fix: modal backdrop was invisible in some browser versions

.changeset/eight-dancers-deliver.md, packages/css/validation-message.css
=> fix(ValidationMessage): add `position: relative`

.changeset/hip-brooms-brush.md, packages/css/alert.css
Add `position: relative;` to the `.ds-alert` class in `packages/css/alert.css`.
* Ensure the icon stays within the component by adding `position: relative;` to the `.ds-alert` class.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/digdir/designsystemet?shareId=753f785f-f7ec-412a-a831-0293680df6b4).
=> fix(alert): add `position: relative`

.changeset/hot-crews-perform.md, packages/react/src/components/Popover/Popover.stories.tsx, packages/react/src/components/Popover/Popover.tsx
resolves #2649
This check the width of both elements, and places the arrow in the center of the shortest one,
=> fix(Popover): place arrow correctly

packages/css/popover.css, packages/css/tooltip.css, packages/react/src/components/Popover/Popover.tsx, packages/react/src/components/Tooltip/Tooltip.tsx
Steamlines so we only use css vars for placement, and all the arrow placement is now done in JS, not JS+CSS.
Was debating wether `${Math.round(...}px` should be a util, but decided not to do it, since it is so far only used in these two components.
=> chore: do arrow placing in code, not css

.changeset/selfish-meals-pump.md, packages/react/src/components/Dropdown/DropdownItem.tsx, packages/react/src/components/Pagination/PaginationButton.tsx, packages/react/src/components/ToggleGroup/ToggleGroupItem.tsx, packages/react/src/components/form/Input/Input.mdx, packages/react/src/components/form/Input/Input.stories.tsx, packages/react/src/components/form/Input/Input.tsx, packages/react/src/components/form/Select/Select.tsx, packages/react/src/components/form/Select/useSelect.ts, packages/react/src/components/form/Textfield/Textfield.mdx, packages/react/src/components/form/Textfield/Textfield.tsx
- Remove `htmlSize` in favor of native `size` on `<Input>` and `<Select>`
- Does not fix old form components as these will be rewritten to extend Input anyway
- Minor typescript clean up as we do no longer need to `Omit<'size'>`
=> fix(Input+Select): remove htmlSize

.changeset/blue-stingrays-heal.md, .changeset/slow-impalas-vanish.md, packages/css/accordion.css, packages/css/label.css, packages/react/src/components/form/Search/Search.test.tsx, packages/react/src/components/form/Search/Search.tsx
resolves #2696
This PR makes `hideLabel` work weird in some form components. This will be looked at when we refactor these, as this has not been done yet. The position relative we added makes our `sr-only` class not set its position absolute.
=> fix: icon abandoning parent

packages/css/breadcrumbs.css
Change meda query for breadcrumbs. Allow coverage for all view ports. Including values between 650px and 651px
=> fix(css): breadcrumbs media query

packages/react/src/components/form/Field/Field.mdx, packages/react/src/components/form/Field/Field.stories.tsx, packages/react/src/components/form/Field/FieldCounter.tsx, packages/react/src/components/form/Field/index.ts
- Created new `Field.Counter` to replace `CharacterCounter`
- Will delete old `CharacterCounter` in #2710 when use is replaced with `Field.Counter` there
- [Example story](https://pr-2717.storybook.designsystemet.no/?path=/story/komponenter-field--counter)
=> refactor(Field): :recycle: merge `CharacterCounter` into `Field`

.changeset/old-sheep-dress.md, packages/react/src/components/Modal/Modal.tsx
Expose native `event` in Modal `onClose` handler
=> fix(Modal): expose event in onClose

.changeset/fifty-hornets-hang.md, apps/storybook/story-utils/customStylesDecorator.tsx, packages/css/base/base.css
- Moves default background to `<body>` element instead of `:root` to align with best practice and avoid conflicts when setting both background on body and :root
- Fixes minor sizing issue on stories with custom css
=> fix: move default background to body element

vite.config.ts
Fix vite complaining about missing random cache files from storybook.
=> chore: fix storybook cache vite error

packages/css/search.css
Minor missed tweak making the button-selectors a little bitt easier, and a little bit smarter as they now also handle `button` without `type` set 😇
=> fix(Search): mini simplification of selectors

.changeset/long-countries-check.md, packages/cli/src/tokens/create.ts, packages/cli/src/tokens/types.ts, packages/cli/src/tokens/write.ts
resolves #2787
Just did the minimum to disable the design-tokens generation for contrast color-scheme. 
We need to do some renaming of types etc, that will be done in #2805
=> feat(cli): :triangular_flag_on_post: disable contrast color-scheme in tokens create script

packages/css/src/index.css
Remove unnecessary `ds.typography` CSS layer now that they just reflect the component. Reduce complexity and avoid confusion with `ds.theme.typography`
=> refactor: :fire: Remove unnecessary `ds.typography` CSS layer

.changeset/silver-penguins-occur.md, packages/react/src/components/Details/Details.mdx, packages/react/src/components/form/Fieldset/Fieldset.stories.tsx
We forgot to add a changeset in #2824, this PR adds one.
=> chore: add missing changeset for `Details` rename

.changeset/ninety-jeans-punch.md, packages/react/package.json
- Set `"type": "module"` in React package to indicate we are building with modern ESM features
=> fix(React): use package type module

apps/_components/src/ClipboardButton/ClipboardButton.tsx, apps/_components/src/CodeSnippet/CodeSnippet.module.css, apps/_components/src/CodeSnippet/CodeSnippet.tsx, apps/_components/src/Footer/Footer.tsx, apps/_components/src/Header/Header.tsx, apps/_components/src/logos/Udir.tsx, apps/storefront/app/bloggen/_components/PostLayout/PostLayout.tsx, apps/storefront/app/grunnleggende/designelementer/farger/page.mdx, apps/storefront/app/grunnleggende/for-utviklere/komposisjon/page.mdx, apps/storefront/app/komponenter/page.tsx, apps/storefront/app/monstre/feilmeldinger/page.mdx, apps/storefront/components/MdxContent/MdxContent.module.css, apps/storefront/components/SidebarMenu/SidebarMenu.tsx, apps/storefront/components/Tokens/TokenList/TokenList.tsx, apps/storefront/layouts/MenuPageLayout/MenuPageLayout.tsx, apps/storefront/tsconfig.json, apps/theme/components/TokenModal/TokenModal.tsx
This PR ports over changes and fixes from #2830
resolves #2840
resolves #2816
New codeblock styling is approved by @Thunear
=> chore: storefront fixes

plugins/figma/manifest.json, plugins/figma/package.json, plugins/figma/src/plugin/figma/themes.ts, plugins/figma/src/plugin/figma/updateVariables.ts, plugins/figma/src/ui/App.css, plugins/figma/src/ui/index.html, plugins/figma/src/ui/pages/Theme/Theme.tsx
this updates the currently broken color regex, and adds future support for multiple colors in `main-colors` and `support-colors`.
Currently it just checks that we have accent and brandX - to match the "current" functionality
=> fix(figma-plugin): update color regex

packages/react/src/components/Modal/Modal.tsx
this button should always be neutral and not follow data-color inheritance
=> chore(Modal): make button always `neutral`

.github/workflows/checks.yml, .github/workflows/test.yml, .vscode/settings.json, apps/_components/declarations.d.ts, apps/_components/package.json, apps/_components/src/Header/Header.tsx, apps/_components/tsconfig.json, apps/storefront/components/Tokens/TokenColor/TokenColor.tsx, apps/storefront/layouts/MenuPageLayout/MenuPageLayout.tsx, apps/storefront/tsconfig.json, apps/storybook/package.json, apps/theme/package.json, package.json, packages/cli/package.json, packages/cli/src/colors/utils.ts, packages/react/package.json, plugins/figma/package.json, plugins/figma/src/ui/pages/Theme/Theme.tsx, yarn.lock
A simple way to type checking all our projects now without relying on third party for now., until we have a look at #2776 
- run `yarn types` to run this check locally
- Checks gh action is noticeably slower now with runtime going for 50s to 1min 20s. I think we are ok with this for now since we have other stuff running longer on PRs. 
- Using [yarn workspaces foreach](https://yarnpkg.com/cli/workspaces/foreach) we run `types` script on all our packages that have it defined.
- Fixed a couple of linting errors and mistakes deleting stuff that was used
- Added `types` script on relevant projects
Current type checked projects
```
[@digdir/designsystemet]
[@digdir/designsystemet-react]
[@designsystemet/storybook]
[@repo/components]
[figma-plugin]
[storefront]
[theme]
```
=> ci: :construction_worker: Add type checks to PR checks

apps/theme/app/page.tsx, apps/theme/app/test/page.tsx, apps/theme/app/testside/page.tsx, apps/theme/app/themebuilder/_utils/useThemeParams.tsx, apps/theme/app/themebuilder/page.tsx, apps/theme/components/ColorContrasts/ColorContrasts.tsx, apps/theme/components/Colors/Colors.tsx, apps/theme/components/ContrastChart/ContrastChart.tsx, apps/theme/components/Scale/Scale.tsx, apps/theme/components/Sidebar/ColorPage/ColorPage.tsx, apps/theme/store.ts, apps/theme/types.ts, packages/cli/src/colors/theme.ts, packages/cli/src/colors/types.ts, packages/cli/src/tokens/create.ts, packages/cli/src/tokens/write.ts, packages/cli/src/tokens/write/generate$metadata.ts, packages/cli/src/tokens/write/generate$themes.ts, plugins/figma/src/ui/pages/Theme/Theme.tsx
resolves #2805
- Renamed `ColorMode` to `ColorScheme`.
- `themeMode` to `colorScheme` or `scheme` depending on usage.
- Fixed & removed other duplicate types so that the same type is used everywhere
=> chore: rename & conform color types

apps/theme/app/page.tsx
If the id is not set or does not match what the SkipLink component uses then the
"skip to content" link does not work. Adding it is a quick fix and makes the
site easier to use for keyboard users.
=> fix(theme): skip link should link to main content

.changeset/wicked-plants-eat.md, packages/css/src/input.css, packages/react/src/components/Select/Select.stories.tsx, packages/react/src/components/Select/Select.tsx
- As discussed https://designsystemet.slack.com/archives/C05U1MNKYCX/p1733498017147069
- `<Select>` follows the width of its widest content, but `<Input>` is automatically full width unless `size` is set
- To make this consistent, we make `<Select>` automatically full width, unless setting `data-width="auto"`
- We're using `data-width="auto"` to avoid conflict with native `<select multiselect size="3">` and `data-size` styling
=> fix(Select): add width auto option

.changeset/fresh-planes-complain.md, .changeset/weak-keys-tap.md, packages/css/src/validation-message.css, packages/react/src/components/Field/FieldCounter.tsx, packages/react/src/components/ValidationMessage/ValidationMessage.tsx
- `Field.Counter` now uses `Paragraph` instead of `ValidationMessage`
- Fixed bug with `ValidationMessage` having wrong default element type
- Removed `neutral` color mappings for `ValidationMessage`
=> refactor: 🔥 Remove `neutral` color for `ValidationMessage`

.changeset/popular-parrots-begin.md, packages/react/src/utilities/types.ts
=> fix(react): don't inline React prop types

.changeset/fair-gorillas-pay.md, packages/css/src/link.css
Fix: Link `underline` when using Tailwind
=> fix(Link): missing underline when using Tailwind

.changeset/great-cameras-check.md, packages/css/src/input.css
=> fix(Switch): adjust design

.changeset/five-mails-pull.md, packages/css/src/table.css, packages/react/src/components/Table/TableHeaderCell.tsx
- Fixes silly border styling error for table footer divider
- Fixes need for add `ds-focus` on sortable button 
- Question; should `table-header-background | divider` be user for `tfoot`? 🤔
=> fix(Table): footer divider and sortable button styling

.github/workflows/deploy-storefront.yml, .github/workflows/deploy-storybook.yml, .github/workflows/deploy-theme.yml, .github/workflows/preview-storefront.yml, .github/workflows/preview-theme.yml
Install with npm instead of yarn seems to work for missing vercel bin
=> ci: :green_heart: Fix unknown vercel bin on CI

.changeset/bright-eyes-beam.md, .changeset/cold-seals-draw.md, apps/_components/src/Showcase/Showcase.tsx, packages/css/src/button.css, packages/css/src/pagination.css, packages/react/src/components/Pagination/Pagination.mdx, packages/react/src/components/Pagination/Pagination.stories.tsx, packages/react/src/components/Pagination/Pagination.test.tsx, packages/react/src/components/Pagination/usePagination.ts, packages/react/src/components/Table/Table.tsx, packages/react/stories/testing.stories.tsx
- Using empty `li` for ellipsis
=> fix(Pagination): use empty li for ellipsis

packages/css/src/avatar.css, packages/css/src/badge.css, packages/css/src/breadcrumbs.css, packages/css/src/card.css, packages/css/src/chip.css, packages/css/src/combobox.css, packages/css/src/details.css, packages/css/src/dropdown.css, packages/css/src/field.css, packages/css/src/pagination.css, packages/css/src/popover.css, packages/css/src/search.css, packages/css/src/skeleton.css, packages/css/src/skiplink.css, packages/css/src/table.css, packages/css/src/tag.css, packages/css/src/togglegroup.css
- Respect `hidden` attribute on all components
- Updated https://github.com/digdir/designsystemet/issues/2450
- Did not fix tabs as this is fixed in https://github.com/digdir/designsystemet/pull/2944/
=> fix: hidden attribute

.changeset/twelve-paws-jog.md, packages/cli/bin/designsystemet.ts, packages/cli/bin/options.ts
=> fix(cli): outDir default wasn't used + remove unwanted console.logs

.changeset/funny-peaches-lie.md, apps/theme/app/result/page.tsx, apps/theme/components/TokenModal/TokenModal.tsx, packages/cli/bin/config.ts, packages/cli/bin/designsystemet.ts, packages/cli/src/tokens/create.ts, packages/cli/src/tokens/index.ts, plugins/figma/src/ui/pages/Theme/Theme.tsx
To facilitate better errors, the CLI option names that also exist in JSON config are now defined in a `cliOptions` object that we can use to look up the mapping between JSON path and CLI option through `mapPathToOptionName(path)`
Before this change:
After:
=> feat(cli): better error messages for wrong or missing options

.changeset/friendly-hotels-behave.md, packages/cli/bin/config.ts, packages/cli/package.json, packages/cli/src/build-scripts/createJsonSchema.ts, packages/cli/test-tokens-create-complex.config.json, packages/cli/test-tokens-create.config.json, yarn.lock
Adds JSON schema for CLI config file, which enables editor hints. To use it, do something like this:
```jsonc
{
"$schema": "node_modules/@digdir/designsystemet/dist/config.schema.json"
// ...config options here...
}
```
Example:
=> feat(cli): add JSON schema for config file

.changeset/mean-starfishes-hear.md, packages/css/src/field.css, packages/react/src/components/Select/Select.stories.tsx
reported on slack.
If an option was inside `disabled`, `Field` would show everything as disabled.
=> fix(field): don't show as disabled when option is disabled

.changeset/fast-cows-impress.md, .changeset/modern-hats-destroy.md, apps/storefront/tokens/altinn/dark.ts, apps/storefront/tokens/altinn/light.ts, apps/storefront/tokens/digdir/dark.ts, apps/storefront/tokens/digdir/light.ts, apps/storefront/tokens/portal/dark.ts, apps/storefront/tokens/portal/light.ts, apps/storefront/tokens/uutilsynet/dark.ts, apps/storefront/tokens/uutilsynet/light.ts, design-tokens/semantic/color.json, packages/cli/src/tokens/design-tokens/template/semantic/color-base-file.json, packages/theme/brand/altinn.css, packages/theme/brand/altinn/color-scheme/dark.css, packages/theme/brand/altinn/color-scheme/light.css, packages/theme/brand/digdir.css, packages/theme/brand/digdir/color-scheme/dark.css, packages/theme/brand/digdir/color-scheme/light.css, packages/theme/brand/portal.css, packages/theme/brand/portal/color-scheme/dark.css, packages/theme/brand/portal/color-scheme/light.css, packages/theme/brand/uutilsynet.css, packages/theme/brand/uutilsynet/color-scheme/dark.css, packages/theme/brand/uutilsynet/color-scheme/light.css
resolves #2985 
`focus-outer` referenced the accent scale, this scale is not static and can change. Neutral is a safer scale to use as a reference here.
=> fix: focus-outer -> neutral.text.default

.changeset/red-gorillas-argue.md, .changeset/unlucky-hairs-sit.md, packages/css/src/tabs.css, packages/react/src/components/Tabs/Tabs.test.tsx, packages/react/src/components/Tabs/TabsList.tsx, packages/react/src/components/Tabs/TabsPanel.tsx, packages/react/src/components/Tabs/TabsTab.tsx, packages/react/src/utilities/RovingFocus/RovingFocusRoot.tsx
Related to #2944 and https://github.com/digdir/designsystemet/issues/2449
Fixes issues found in #2355
=> chore(Tabs): rework component

.changeset/hip-weeks-fetch.md, packages/cli/tsup.config.ts
Fix bug with missing files in dist build
=> fix(cli): :ambulance: include missing build files in for `designsystemet`bin

.changeset/new-kangaroos-count.md, packages/react/src/components/Popover/PopoverTrigger.tsx, packages/react/src/components/Tooltip/Tooltip.tsx
Fixes the errors flagged by nextjs of "invalid" react props.
=> fix: :bug: Use correct popover api attributes based on React version

README.md, apps/storefront/app/grunnleggende/designelementer/typografi/page.mdx, apps/storefront/globals.css, apps/storybook/.storybook/manager-head.html, apps/storybook/.storybook/preview-head.html, apps/theme/app/globals.css, packages/get-started.mdx, packages/react/stories/Typography.mdx, plugins/figma/src/ui/index.html
=> style: inter v4

packages/css/src/field.css
Just fixing this one off, but we should have a closer look at other components for this use-case.
- `ds-input` should probably be updated to use less re-assignments for variants
- split use of `border` into the 3 separate CSS props
=> fix(field): :lipstick: fix broken invalid styling for `ds-input` inside `Field`

packages/css/src/base.css, packages/css/src/field.css, packages/css/src/fieldset.css, packages/css/src/input.css, packages/css/src/label.css, packages/css/src/modal.css, packages/css/src/skeleton.css, packages/css/src/spinner.css
resolves #3071
- Use `--_ds*` naming convention for internal tokens
- Avoid custom property reassignment for animation durations
=> fix: use _dsc internal css custom property naming convetion

packages/cli/src/colors/utils.ts
Add the base prefix to the contrast color names in the `getColorInfoFromPosition` function.
In the themebuilder the preview examples loop through the function to set unique tokens for each card. Now the contrast colors are not applied because the base prefix is missing. When a very light color is selected in the themebuilder, the text in the Button on the preview Cards are white.
=> chore: fix wrong color name returned from CLI func

.changeset/long-taxis-tease.md, packages/react/src/utilities/hooks/useCheckboxGroup/useCheckboxGroup.ts, packages/react/src/utilities/hooks/useRadioGroup/useRadioGroup.ts
Fixes bug reported in by slack, when using our `useCheckboxGroup` and `useRadioGroup` with respective `Checkbox` and `Radio` component.
This was probably due to changes in types used for `forwardRef` in React 19.
```sh
Type '{ name?: string | undefined; title?: string | undefined; description?: ReactNode; placeholder?: string | undefined; form?: string | undefined; onChange?: ChangeEventHandler<HTMLInputElement> | undefined; ... 288 more ...; label: string; }' is not assignable to type 'RefAttributes<HTMLInputElement>'.
Types of property ref are incompatible.
```
=> fix: `ref` type on `useCheckboxGroup` and `useRadioGroup`

apps/storefront/app/bloggen/2025/generering-av-fargar-i-fargesystemet/page.mdx
=> chore: fix metadata for newest blog article

.changeset/gorgeous-lizards-begin.md, packages/css/src/dialog.css
- Only add `overflow: hidden` to `<body>` if opened by `.showModal()` (not when non-modal `.show()`)
- Use `top: 50%; left: 50%; transform: -50% -50%` for positioning instead of `margin: auto; inset: 0` as the latter does not center `<dialog>` if placed inside a `display: flex`
=> fix(Dialog): non-modal and support position in display: flex

.changeset/cyan-bears-brush.md, .changeset/fluffy-moose-swim.md, packages/css/src/table.css
=> feat(Table): new colors on zebra and hover

.changeset/fluffy-pears-pull.md, packages/css/src/badge.css
fixes an empty badge not being displayed:
=> fix(Badge): allow empty badge

.changeset/serious-readers-marry.md, packages/css/src/dialog.css
- Add missing `overflow: auto`
- Position with `transform` so animation with `translate` is easier
=> fix(Dialog): add missing overflow: auto

apps/theme/components/TokenModal/TokenModal.tsx
fixes wrong hex color being picked for cli snippet
before:
after:
=> fix(theme): should pick correct color for cli snippet

apps/_components/src/ColorModal/ColorModal.tsx, apps/storefront/components/Tokens/TokenColor/TokenColor.module.css, apps/storefront/components/Tokens/TokenColor/TokenColor.tsx, apps/theme/app/page.tsx, apps/theme/app/testside/BackgroundSurface/BackgroundSurface.tsx, apps/theme/app/testside/BaseContrast/BaseContrast.tsx, apps/theme/app/testside/Interaction/Interaction.tsx, apps/theme/app/testside/page.tsx, apps/theme/app/themebuilder/_components/ThemePages.tsx, apps/theme/components/ColorContrasts/ColorContrasts.tsx, apps/theme/components/ColorPreview/ColorPreview.tsx, apps/theme/components/ContrastChart/ContrastChart.tsx, apps/theme/components/Group/Group.tsx, apps/theme/components/Previews/Previews.tsx, apps/theme/components/Scale/Scale.tsx, apps/theme/components/TokenModal/TokenModal.tsx, apps/theme/store.ts, packages/cli/src/colors/colorMetadata.ts, packages/cli/src/colors/theme.ts, packages/cli/src/colors/types.ts, packages/cli/src/colors/utils.ts, packages/cli/src/tokens/create.ts
In an effort to prevent bugs related to using indexs for fetching arbitary colors I have introduces stricter types for colorMetaData making safer lookups by name or number
=> refactor(color): :label: better type safety using colors in code

.github/workflows/release.yml, packages/cli/package.json, packages/css/package.json, packages/react/package.json, packages/theme/package.json
Update release ci to work as follows.
We work primarily against `next` and release to `latest` from `next` to make sure everything stays in sync with using [changesets prerelease mode](https://github.com/changesets/changesets/blob/main/docs/prereleases.md) and its files used for tracking whats prerelease and release. 
- Commits to `next` enters prerelease mode if we are not in prerelease mode
- All changesets made into `next` will by default make a new `@next` release
- When we want to release to `latest`, we use then "Exit prerelease mode" (`release-pre-exit.yml`)
- Changesets bot will then detect our intention to exit-prerelease and make a new release PR that will publish to `latest`
- If we are no longer in prerelease mode and changesets have published, we assume a new version to …
=> chore: update release ci

.changeset/nine-worms-spend.md, .changeset/sour-tips-poke.md, apps/storefront/app/bloggen/_components/Card/BlogCard.tsx, apps/storefront/app/god-praksis/tilgjengelighet/kontrast/page.mdx, apps/storefront/app/monstre/feilmeldinger/page.mdx, apps/storefront/app/monstre/obligatoriske-og-valgfrie-felt/page.mdx, apps/storefront/app/monstre/systemvarsler/page.mdx, packages/react/src/components/Badge/Badge.mdx, packages/react/src/components/Badge/Badge.stories.tsx, packages/react/src/components/Badge/Badge.tsx, packages/react/src/components/Card/Card.stories.tsx, packages/react/src/components/Card/Card.tsx, packages/react/src/components/Details/Details.stories.tsx, packages/react/src/components/Details/Details.tsx, packages/react/src/components/Popover/Popover.mdx, packages/react/src/components/Popover/Popover.stories.tsx, packages/react/src/components/Popover/Popover.tsx, packages/react/src/components/ToggleGroup/ToggleGroupItem.tsx
The only `data-*` props in the React component API is now:
- `data-color-scheme`
- `data-color`
- `data-size`
These are special, since they apply to regular HTML elements and also affect descendants.
The rest of our API now consistently does **not** use the `data-` prefix, even if a `data-` attribute is used internally for the implementation. This ensures a clear distinction between React props and global-affecting attributes in our API.
=> feat: ensure consistent usage of `data-*` vs `*` props in React

apps/theme/components/Sidebar/ColorPage/ColorPage.tsx, apps/theme/components/Sidebar/ColorPane/ColorPane.tsx
* Renamed the color labels to "main" and "support" in the sidebar to better match what the colors are named in figma and code.
* Updated the description of the color input to "Bruk kun bokstavene a-z, tall og bindestrek" to better communicate with the user that they cant use "æøå". This was a suggestion from Brreg.
=> chore: update color description and labels in themebuilder

.changeset/seven-hornets-cheat.md, packages/css/src/breadcrumbs.css
fixes this:
it is now this:
but keeps the arrows the same color as link when listed out:
=> style(Breadcrumbs): make arrow in link inherit color

.changeset/happy-hornets-lie.md, packages/css/src/tabs.css
fixes this, where the active line is above the focus border:
it is now this:
=> style(Tabs): focus border above active line

.changeset/old-monkeys-grab.md, packages/css/src/dropdown.css
we changed the arrow size of `Popover`. This moved the dropdown further away from its trigger:
changed to this:
=> style(dropdown): move closer to trigger

apps/_components/src/ColorModal/ColorModal.module.css, apps/storefront/app/(frontpage)/layout.module.css, apps/storefront/app/bloggen/2025/helptext-blir-fjerna-kva-gjer-du/page.mdx, apps/theme/app/globals.css, apps/theme/app/page.module.css, apps/theme/app/themebuilder/page.module.css, apps/theme/components/ColorContrasts/ColorContrasts.module.css, apps/theme/components/ColorContrasts/ColorContrasts.tsx, apps/theme/components/ColorPreview/ColorPreview.module.css, apps/theme/components/ColorPreview/ColorPreview.tsx, apps/theme/components/ColorTokens/ColorTokens.tsx, apps/theme/components/OverviewComponents/OverviewComponents.module.css, apps/theme/components/OverviewComponents/TableCard/TableCard.module.css, apps/theme/components/OverviewComponents/TableCard/TableCard.tsx, apps/theme/components/Previews/Previews.module.css, apps/theme/components/Sidebar/Sidebar.module.css, apps/theme/components/Sidebar/Sidebar.tsx, apps/theme/components/ThemeHeader/ThemeHeader.module.css
related to #3232
resolves #3234
=> chore: fix misc layout things

apps/storybook/stories/showcase.stories.tsx, packages/react/src/components/Dialog/Dialog.stories.tsx, packages/react/src/components/MultiSuggestion/MultiSuggestion.stories.tsx, packages/react/src/components/Suggestion/Suggestion.stories.tsx
resolves #3245 
I do not get any violations if I re-enable `aria-allowed-attr` rule, so I have removed this.
The "combobox role not allowed on input" problem in `Suggestion`/`Multisuggestion` seems to possibly stem from [this](https://github.com/dequelabs/axe-core/issues/4672) reported issue in axe-core. 
> The logic axe-core uses vs the logic the spec uses for determining when text/tel/url/email/search should be treated as comboboxes is also slightly different; the spec says that the presence of a list attribute is enough that it should be treated as combobox-like, but axe-core demands that it not just have a list attribute but that the list attribute be a valid idrefs-style reference to a datalist element (html-elms.js is inconsistent with implicit-html-roles.js and just looks for any …
=> chore(apps): updates to disabled sb a11y tests

.github/workflows/check-changeset.yml
Changeset-check fails if only mdx-files are changed
Dont fail the changeset-check if only mdx-files are changed
=> ci(check-changeset): ignore mdx-files

apps/storefront/app/bloggen/_components/Card/BlogCard.tsx
The blog-cards should be white in light mode, to look good against the grey background.
=> chore: remove tinted value from blog-cards in storefront

.changeset/fresh-dogs-join.md, .changeset/tasty-cats-rescue.md, packages/css/src/base.css, packages/css/src/field.css, packages/css/src/fieldset.css, packages/css/src/label.css, packages/react/src/components/Suggestion/Suggestion.tsx
Long time no see!
- We want to use as pure HTML as possible in Mattilsynet
- Currently, logic adding/hiding lock icon for read only field/fieldset is scattered across field+fieldset+label (which is also used `as="legend"`)
- By moving this into a base utility we can compose into field/fieldset, the logic is a little bit more readable - we remove a css custom property trick, and the label component no longer "communicates" with other files
- This also makes label/legend component optional - for us in Mattilsynet, we can jsut use pure HTML without any additional classnames <3
=> fix: move readonly logic to field/fieldset making label/legend components optional

.changeset/slow-bugs-relate.md, packages/react/src/components/Tooltip/Tooltip.tsx
Adds `autoPlacement` to Tooltip to better align with `Popover`, which is also a floating element that has this prop.
=> feat(Tooltip): add `autoPlacement` prop

.changeset/full-bats-smash.md, packages/css/package.json, packages/css/types.d.ts
resolves #3366
Conform imports on our packages. 
`css` package was the only one without types making it flag as type error, when importing when `theme` package works fine.
Added types so it matches behaviour of our other packages when importing in typescript. 
`import '@digdir/designsystemet-css';`
=> feat(css): add empty typings for easier import in typescript

.changeset/metal-beers-stand.md, packages/cli/src/tokens/create/generators/$designsystemet.ts, packages/cli/src/tokens/create/write.ts
resolves #3496
Adds a file which includes name and version from `package.json` used to create tokens.
```
{
"name": "@digdir/designsystemet",
"version": "1.0.3"
}
```
=> feat(cli): add metadata file for `tokens create`

apps/storybook/story-utils/transformSource.ts, packages/react/src/components/Alert/Alert.stories.tsx
Follow up from #3572
- Make `formatReactSource` not disable the html output from the default transform function, which makes it usable also in future situations when the auto-generated html is good enough (without using `ReactOrHtmlCanvas`)
- Add some comments to live region examples in React, same as was done in the html examples, to make the difference between the two examples more obvious
=> docs(Alert): small follow-up for live region refinement

apps/storybook/story-utils/extractRenderedHtml.ts, apps/storybook/story-utils/transformSource.ts
This works more consistently than `ReactDOMServer.renderToStaticMarkup`, for instance when a React context is used. An example of `renderToStaticMarkup` not being sufficient is [this ErrorSummary story](https://next.storybook.designsystemet.no/?path=/docs/komponenter-errorsummary--docs&globals=codePreview:html#bruk-med-tekstfelt).
As a bonus, this PR also ensures the html preview is updated whenever story args change by users interacting with the props table.
Storybook's low-level channel API, which is used here, is accessed through `DocsContext` which is exported publically. The event names themselves are not exported or documented except in the source code, but are available through `channel.eventNames()`.
Hopefully this code can be simplified in the future if Storybook introduces async …
=> docs: use rendered html for code examples and update when args change

packages/react/src/components/Alert/Alert.mdx
- “enkelte skjemaelement” kan enkelt misforståast som “i noen tilfeller”
- på bokmål har vi vel elles brukt “elementer/elementene”  sjølv om “element/elementa” er lov
- halvparten av lista hadde ", bruk heller ..." og halvparten har "(bruk heller …)"
=> docs(Alert): small text change for clarity and consistency

biome.jsonc, plugins/figma/package.json, pnpm-lock.yaml
Could not find this used anywhere. Plugin still builds fine. This means we can remove PR #3596
=> chore: remove `npm-run-all2`

.changeset/odd-kings-lead.md, README.md, packages/css/src/tooltip.css, packages/get-started.mdx, packages/react/src/components/Popover/Popover.mdx, packages/react/src/components/Tooltip/Tooltip.mdx
resolves #3444 
also adds support for the polyfill in `tooltip` by adding a selector for the `.\:popover-open` replacement class this uses.
=> chore: document popover polyfll

.changeset/petite-cobras-buy.md, packages/theme/package.json
Fixes missing default export when importing using just package name.
```js
import '@digdir/designsystemet-theme'
```
Test using https://unpkg.com/@digdir/designsystemet-theme@test
=> fix(theme): add missing default file export

plugins/figma/package.json, plugins/figma/src/common/dummyTheme.ts, plugins/figma/src/common/store.ts, plugins/figma/src/common/types.ts, plugins/figma/src/plugin/figma/updateVariables.ts, plugins/figma/src/plugin/plugin.ts, plugins/figma/src/ui/pages/Theme/Theme.tsx, plugins/figma/src/ui/pages/Themes/Themes.tsx, pnpm-lock.yaml
Hotfix to update to new default theme color names and feedback.
- Changed hardcoded color names to match new default theme. Will update this to actually pick colors from default theme in a separate PR.
- Updated error message to show which required colors are missing in pasted snippet.
- Updated wording and info box about required colors.
=> fix: update plugin to latest theme colors

.changeset/nasty-owls-pay.md, packages/css/src/tooltip.css, packages/react/src/components/Tooltip/Tooltip.tsx
resolves #2941
This is fixed by just adding a transparent (in the picture red) `::after` element, and then adding the same mouse listeners to the tooltip.
=> chore(tooltip): stays open when mouse is inside

.changeset/clean-seals-shake.md, packages/cli/bin/config.ts, packages/cli/src/config.ts, packages/cli/src/scripts/createJsonSchema.ts
Fix error message downstream when running `tokens create --config` and defaulting to default values.
- Removed double `zod.parse` in validate and parse config functions. Only in validate function now as it validates schema during parse.
- Updated `zod-validation-error` to v4
- Added better fallback for when `zod-validation-error` fails to parse friendly error message
- Changed some type names related to config for better readability. 
- [ x ] I have read the [contribution guidelines](https://github.com/digdir/designsystemet/blob/main/CONTRIBUTING.md)
- [ x ] I have added a changeset (run `pnpm changeset` if relevant)
=> fix(cli): zod schema error when creating tokens from config file

.changeset/sweet-shoes-juggle.md, packages/react/src/components/Suggestion/Suggestion.stories.tsx, packages/react/src/components/Suggestion/Suggestion.tsx
- Adds tests for rendering of controlled state in Suggestion component (stories ControlledSingle and ControlledMultiple).
- Fixes that the test fails for ControlledSingle, because of a bug / ommision upstream in u-combobox: https://github.com/u-elements/u-elements/issues/25
=> fix(Suggestion): controlled state for single-suggestion didn't render correctly

.changeset/silver-adults-pay.md, packages/css/src/details.css
I offer an alternative to #3609 that should effectively do the same but without breaking the animation.
=> fix(Detail): one padding when multiple children

.changeset/mean-mails-bake.md, packages/react/src/components/Suggestion/Suggestion.stories.tsx, packages/react/src/components/Suggestion/Suggestion.tsx
Fixes a crash in Suggestion which occurs only when changing the value if the initial value was an empty string
```
DOMException: Node.removeChild: The node to be removed is not a child of this node
The above error occurred in the <data> component.
```
=> fix(Suggestion): empty string as initial value led to crash when changing value

apps/www/scripts/copy-content.js
Disables a bunch of files being copied to root causing over 100 untracked files when working locally.
=> chore(www): disable copy files to root

.changeset/many-jobs-teach.md, .changeset/poor-ways-boil.md, .changeset/wise-emus-deny.md, packages/css/src/details.css, packages/css/src/table.css, packages/css/src/tabs.css
- `Table` sorting icon never shrinks, even when using `Button` component (which is `display: flex`) as parent
- `Table` with `data-border` adjusts `border-radius` according to `border-width`
- `Details` content using `overflow: hidden` to prevent margin clipping
- `Tabs` adjusted to allow non-tab-button-elements inside `tablist`
=> fix: mattilsynet css fixes

.changeset/short-wolves-move.md, packages/react/package.json, packages/react/src/components/suggestion/index.ts, packages/react/src/components/suggestion/suggestion-chips.tsx, packages/react/src/components/suggestion/suggestion-input.tsx, packages/react/src/components/suggestion/suggestion-list.tsx, packages/react/src/components/suggestion/suggestion-option.tsx, packages/react/src/components/suggestion/suggestion.mdx, packages/react/src/components/suggestion/suggestion.stories.tsx, packages/react/src/components/suggestion/suggestion.tsx, pnpm-lock.yaml
- Deprecated `Suggestion.Chips` as this always needs to render
- `renderSelected` added to `Suggestion`
- `onBeforeMatch` added to `Suggestion`
- `u-combobox` updated, so value is reverted instead of cleared when there is no match
- `value`/`defaultValue`/`onValueChange` deprecated and replaced by `selected`/`defaultSelected`/`onSelectedChange`
- Part of #3851
=> fix(Suggestion): include chips and onbeforematch

.changeset/lemon-cows-remember.md, packages/css/src/details.css, packages/react/src/components/details/details.stories.tsx
Details element is [supposed to support direct children](https://github.com/digdir/designsystemet/pull/3796), but due to CSS selector specificity, elements with `padding` or `border-radius` (such as buttons) broke. This branch fixes the issue.
=> fix(Details): enhance direct content support

.changeset/eleven-cats-brake.md, .changeset/silent-poems-nail.md, .changeset/strange-ears-speak.md, packages/react/package.json, packages/react/src/components/dialog/dialog.tsx, pnpm-lock.yaml
resolves #3904
resolves #3902
also updates u-combobox and u-datalist, where ESC click now uses `preventDefault()`
=> fix(dialog): respect default prevented events

.changeset/lucky-pandas-see.md, packages/css/src/badge.css, packages/react/src/components/badge/badge.stories.tsx
Adds support (through css variables) and fixes example story for custom positioning of Badge. The example didn't actually move the badge, but now it does.
=> fix(badge): allow custom positioning

.changeset/lucky-ghosts-make.md, design-tokens/$designsystemet.jsonc, internal/design-tokens/$designsystemet.jsonc, packages/cli/src/scripts/update-design-tokens.ts, packages/cli/src/tokens/build.ts, packages/cli/src/tokens/create/write.ts, packages/theme/brand/altinn.css, packages/theme/brand/colors.d.ts, packages/theme/brand/digdir.css, packages/theme/brand/portal.css, packages/theme/brand/types.d.ts, packages/theme/brand/uutilsynet.css, packages/theme/src/themes/colors.d.ts, packages/theme/src/themes/designsystemet.css, packages/theme/src/themes/types.d.ts
resolves #3790
I propose we just rename the config file to $designsystemet.jsonc. It does not make a difference to us and token-studio will ignore it then.
=> fix(cli): rename config so token-studio ignores it

.changeset/short-teams-design.md, packages/react/src/components/switch/switch.tsx
`label` prop on `Switch` incorrectly has the jsdoc description "Radio label". Changed to "Switch label".
=> fix(Switch): correct jsdoc on `label` prop

apps/themebuilder/app/_components/sidebar/sidebar.module.css, apps/themebuilder/app/app.css, apps/www/app/app.css, internal/components/src/header/header.module.css, internal/components/src/header/header.tsx
resolves #4011 
- Fixed skip-link being clipped behind header
- Fixed tab-order of header elements in mobile view
- mobile menu if open is closed when tabbing out of the header
- Added logic to restore to desktop mode when resizing window up again (its still dynamic js instead of media query) 
- themebuilder: fixed the sidebar toggle button overlaying the mobile menu
since `reading-flow: flex-visual;` is only in chromium for now I opted to create a conditionally rendered mobile only menu after the hamburger button so it works in all browsers
=> fix(www, themebuilder): header a11y fixes

apps/storybook/.storybook/main.ts, apps/storybook/package.json, pnpm-lock.yaml
The plugin is still not showing formatted html after new release and does not work well in dark mode, so we'll remove it. html output can still be seen in the docs pages as this uses our own custom code and of course in the new storefront component pages
=> chore(storybook): remove addon-html plugin

.changeset/rotten-pans-ring.md, packages/react/src/components/field/field-counter.tsx, packages/react/src/components/textfield/textfield.stories.tsx, packages/react/src/components/textfield/textfield.test.tsx
resolves #3900
This is **NOT** an ideal solution, but I think this is fine.
It will rerender anyways, and a page will most likely not have a lot of counters, so this should not cause any huge performance impacts.
See https://pr-4047.storybook.designsystemet.no/?path=/story/komponenter-textfield--controlled
=> fix(Field.Counter): update when react controls input

.changeset/unlucky-wombats-dream.md, packages/react/src/components/popover/popover.test.tsx, packages/react/src/components/popover/popover.tsx
=> fix(Popover): only call `onClose` when popover is open

.changeset/cruel-breads-see.md, apps/www/app/_components/tokens/design-tokens/type-scale.json, design-tokens/$designsystemet.jsonc, internal/design-tokens/$designsystemet.jsonc, packages/cli/src/tokens/process/formats/css/size.ts, packages/cli/src/tokens/process/formats/css/type-scale.ts, packages/theme/brand/altinn.css, packages/theme/brand/colors.d.ts, packages/theme/brand/digdir.css, packages/theme/brand/portal.css, packages/theme/brand/types.d.ts, packages/theme/brand/uutilsynet.css, packages/theme/src/themes/colors.d.ts, packages/theme/src/themes/designsystemet.css, packages/theme/src/themes/types.d.ts
Font size variables are now rounded to the nearest pixel. This affects size modes "sm" and "lg", which had subpixel values after v1.5.0 / #3866
=> fix(cli,theme): round font variables

.changeset/silver-buttons-shine.md, .github/workflows/test-visual.yml, packages/css/src/chip.css, packages/css/src/tag.css
**Chip, Tag**: Ensure font size scales correctly with the current size mode by using the token `--ds-body-sm-font-size`. Note: there might be a small visual change for `Chip` used without explicit `data-size`, since it used to have `font-size: 90%`.
Closes: #3604
=> fix(css): ensure font-size for Tag and Chip scales correctly with data-size
